### PR TITLE
Fix log path when you run `ant run`

### PR DESCRIPTION
**Pull request by mattiabertorello**
When the IDE was started with `ant run` the log folder was wrong due to a premature initialization of the logging environment before set the log directory path.

### CODE REVIEW

**Comment by cmaglie** [comment]
I've cherry-picked the first two commits but still not working for me, it still creates the `${sys:log4j.dir}`.

**Comment by mattiabertorello** [comment]
The last two commits fix the problem this is the line that must delete it https://github.com/arduino/Arduino/pull/9093/commits/9dd4c735a8ca9bac8a4aec9f01dd552c927ca9d0#diff-6ccded341b7bbb710383be5a14f6529aL63

To address better this problem you need to refactor the setting folder path generation in a way that can be used in the custom configuration of log4j https://logging.apache.org/log4j/2.x/manual/customconfig.html

**Comment by cmaglie** [comment]
Ah now I see, that's the reason why you also extracted BoardCloudResolver! it wasn't clear at a first sight they looked more like two unrelated changes, this is the kind of things that it's worth explaining it in the commit message.

**Comment by mattiabertorello** [comment]
Yes you are right, I should put in commit message

**Pull request merged**
