### PR TITLE
[Lib Manager] Avoid updating the UI at every keystroke

### LINKED ISSUE #8282: [Library manager] Please consider buffering the search flield.
Currently the search field is permanently polled and searches are running while you type.

On weak systems e.g. a RaspberryPi it leads to awful lags. 
It would have been an improvement to buffer the search field and to start a search only after a return has been registered.

Thank you for considering.

### PR DESCRIPTION
**Pull request by facchinm**
Fixes #8282 
Only updates on Return key pressed; to be discussed if a timer based implementation is preferable (so the update on keystroke is maintained but the event is fired after some inactivity)

### CODE REVIEW

**Comment by facchinm** [comment]
@per1234 thanks for the feedback, I just added a commit to reintroduce the "responsive search" with a grace period, while leaving the "immediate search" on RETURN. Let me know if it's better :wink:

**Comment by matthijskooijman** [comment]
Sounds good to me!

**Comment by facchinm** [comment]
@cmaglie can you merge it? :smile:

**Comment by rin67630** [comment]
I hope to get the LinuxARM Build soon to test. 
On a weak RaspberryPi Zero this will be a life saver!
Thanks for implementing

**Comment by per1234** [comment]
@rin67630 now that this PR has been merged, the test builds at the links above have been deleted. This is because this work is now integrated into the hourly build, which you can download here:
https://www.arduino.cc/en/Main/Software#hourly

**Pull request merged**
