### PR TITLE
Added labels to legend

### PR DESCRIPTION
**Pull request by chromhelm**
Supports CSV style header and colon separated <label>:<value>.
It is enough to send the label once they are kept until a new label is send.
Multiply values should be separated by space character.  <label1>:<value1> <label2>:<value2> ...
If can send values only or mixed width labels like this:
  <label1>:<value1> <value2> <value3>  <label4>:<value4> ...
If you send one value you have to send al values. It will corrupt the visualisation.
 !!! NOT ALLOWED !!! <label1>:  <value2> <value3>  <label4>:<value4> ...
Labels can be set without sending data:
   <label1>: <label2>: ...

When using the CSV header style you just send space separated. OBS number only headers do not work. they are only allowed with colon separated style.

### CODE REVIEW

**Comment by jottr** [comment]
@facchinm will this be merged at some point?

**Comment by facchinm** [comment]
I think we can merge it, but some documentation must be added too

**Comment by per1234** [comment]
@facchinm I'm guessing you mean user-targeted documentation rather than just comments in the source code. I completely agree that it's important do document this feature, otherwise the users will not know it's there.

My understanding is that the Serial Plotter is only documented via the following examples:
- https://github.com/arduino/Arduino/blob/master/build/shared/examples/01.Basics/AnalogReadSerial/AnalogReadSerial.ino
- https://github.com/arduino/Arduino/blob/master/build/shared/examples/01.Basics/ReadAnalogVoltage/ReadAnalogVoltage.ino

and the following library examples (and their associated tutorials:
- https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/I2S/examples/InputSerialPlotter/InputSerialPlotter.ino / https://www.arduino.cc/en/Tutorial/I2SInputSerialPlotter
- https://github.com/arduino-libraries/ArduinoSound/blob/master/examples/SpectrumSerialPlotter/SpectrumSerialPlotter.ino / https://www.arduino.cc/en/Tutorial/ArduinoSoundSpectrumSerialPlotter
- https://github.com/arduino-libraries/ArduinoSound/blob/master/examples/AmplitudeSerialPlotter/AmplitudeSerialPlotter.ino / https://www.arduino.cc/en/Tutorial/ArduinoSoundAmplitudeSerialPlotter

and this ArduinoSound library reference example:
- https://www.arduino.cc/en/Reference/FFTAnalyzerRead

I feel that adding a demonstration of the label feature to either of those built-in examples might overly complicate them since they're in the "Basics" section.

It would be more appropriate in the library examples, but that is hiding the label documentation pretty deeply.

I have thought it would be good to provide some formal documentation of the Serial Plotter (https://github.com/arduino/Arduino/issues/5651). Where do you envision the documentation of the new label functionality being added? I was thinking the IDE guide was the best place for it, but perhaps the more detailed documentation of the Serial Plotter (allowed delimiters, labels) will be too much for that page and deserves a page of its own, which would be linked to from the summary description of the Serial Plotter on the IDE guide page.

I'm happy to help with this. I would be limited to providing suggested text for the documentation, which would need to be implemented by someone else, since I don't have edit access to the documentation content. Even so, that would take care of some of the job.

**Comment by facchinm** [comment]
Serial plotter surely needs some love, both from the "inline" documentation and from the website doc. We should coordinate with @SimonePDA to find the right spot where these documentation should be added but I really like the way you want to tackle it!

**Comment by chromhelm** [comment]
Hi
I have uploaded a small protocol description for the label functionality.
https://github.com/chromhelm/Arduino/commit/cdd66b63f686ebe3535dd5fc5f6b9cc592ce8263

**Comment by chromhelm** [comment]
The legend is right now only shown when there is more than one data set. Should I change that so it is always shown ?

**Comment by chromhelm** [comment]
Hi
Thank you for the feedback.
One way to get an arm build is to clone the repository to your am bord and run it from there, but i have newer tried it by myself.

I think it is an good idear to add '|' sign as additional part seperator.

I think the arduino team has do decide what diretion the serialPlotter should take.

[Open PR on SerialPlotter](https://github.com/arduino/Arduino/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+Plotter+OR+SerialPlotter+OR+Ringbuffer)  
[Open issues on SerialPlotter](https://github.com/arduino/Arduino/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Plotter+OR+SerialPlotter+)

Regards

**Comment by per1234** [comment]
>Where can I find an ARM Build to test?

@rin67630 assuming you mean 32-bit ARM Linux, it's the last link in the list of builds provided by ArduinoBot:
https://github.com/arduino/Arduino/pull/7453#issuecomment-380362069

The only changes made to this PR since that build are the addition of documentation files, so it is functionally identical.

**Comment by rin67630** [comment]
> I think it is an good idear to add '|' sign as additional part seperator.
> 

It currently works well with " | " (pipe sign between spaces), no need to write additional code.
If possible, ignoring what is between /* ... */ would have been more useful.

**Comment by facchinm** [comment]
Rebased and manually merged, thanks!

**Pull request closed without merging**
