### PR TITLE
Git integration inside the IDE (commit only)

### PR DESCRIPTION
**Pull request by baydindima**
Сompletely rewrote the code #4704. Now I am using library for work with Git. Now you can init new repository, commit and log commits. This is solve the issue  #4387.
@cmaglie please review and comment my solution.

### CODE REVIEW

**Comment by carlosperate** [comment]
Just for reference, relating this other PR here: https://github.com/arduino/Arduino/pull/4816

**Comment by baydindima** [comment]
Added ability to perform diff and reset.

**Comment by baydindima** [comment]
Added GUI for Diff

**Comment by cmaglie** [comment]
wow, three pull request for git integration in three weeks. It seems that there is a very compelling need to add Git to the Arduino IDE

@carlosperate @baydindima 
I see that you, both, added more features than the original poster asked in #4704. Probably you felt the need to have something more than just a "Commit" command, but even now that those "extra" features are there, they are poorly implemented and leaves a lot to desire. BTW I'm not listing here what works and what not, this is not the purpose of this message and I don't want to do GUI design considerations here, what I want to know from you guys, is if you are willing to invest time to work seriously on this feature. As I already said a proper Git integration (even only the basic commands) is a project on his own.

If the answer is yes, you should probably start the git integration as an Arduino IDE Tool Plugin, in his own repository so people can start to tinker with it and give feedbacks. Here some examples:

https://github.com/esp8266/arduino-esp8266fs-plugin
https://github.com/me-no-dev/EspExceptionDecoder
https://github.com/sandeepmistry/arduino-nRF5/tree/master/extras/ide-tools

Moreover I'd like to see you cooperate instead of competing each other, developers time is a scarce resource!

**Comment by carlosperate** [comment]
@cmaglie, I think you meant @CarlosMiguelCuevas, posting here so that he can get the notification as well.

**Comment by cmaglie** [comment]
oh yes thanks! sorry for the confusion

**Comment by fededim** [comment]
Any plan solve the conflicts and to merge this PR ?

**Comment by silbo** [comment]
Awesome stuff, would be epic to see it in production.
This work just stopped ? Anyone working on merging it ?

**Comment by CarlosMiguelCuevas** [comment]
@cmaglie  I won't be able to continue working on this, actually, I just closed my PR (if someone is interested in the code, the branch was not deleted so the code is there). I didn't check @baydindima 's code but it seems he went furder. so make it happen and good luck.

**Pull request closed without merging**
