### PR TITLE
Introducing fullscreen, aka no distraction mode. Fixes #1246

### LINKED ISSUE #1246: Add a "Full Screen" or "Distraction-Free" mode
Adding a mode that takes over the screen would allow teachers to get students to focus just on the Arduino environment, without distractions. Could be useful for classes of smaller kids.

### PR DESCRIPTION
**Pull request by ffissore**
/cc @tigoe @damellis please give this build a try as soon as @ArduinoBot will have prepared it

### CODE REVIEW

**Comment by damellis** [comment]
If I open a sketch from my sketchbook, make it full screen, and then try to create a new sketch, I get a NullPointerException:

```
java.lang.NullPointerException
	at processing.app.legacy.PApplet.str(PApplet.java:562)
	at processing.app.Base.storeSketches(Base.java:618)
	at processing.app.Base.handleOpen(Base.java:899)
	at processing.app.Base.handleOpen(Base.java:872)
	at processing.app.Base.handleOpen(Base.java:868)
	at processing.app.Base.handleNew(Base.java:759)
	at processing.app.Editor$6.actionPerformed(Editor.java:585)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Similar error if I try to quit:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.legacy.PApplet.str(PApplet.java:562)
	at processing.app.Base.storeSketches(Base.java:618)
	at processing.app.Base.handleQuit(Base.java:979)
	at processing.app.macosx.ThinkDifferent$4.handleQuitRequestWith(ThinkDifferent.java:87)
	at com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:395)
	at com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:388)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This doesn't seem to happen if the full-screen sketch is new (i.e. not in my sketchbook) or if the sketchbook sketch isn't full screen.

**Comment by damellis** [comment]
Also, on Mac, I don't think we should have a toolbar icon, as using the green dot in the window titlebar is standard. (Most applications also have "Enter Full Screen" / "Exit Full Screen" in their View menu, but I haven't found any with a toolbar icon.) I'm not sure what the conventions are on other operating systems, but it would be good to follow them.

**Comment by tigoe** [comment]
I'm confused because this feature is already available (in OSX at least) just by maximizing the window. What's the difference between that way and doing it this way. 

The toolbar icon seems good to me. See Vimeo and YouTube for good precedents on that.

**Comment by carlosperate** [comment]
I can confirm the NullPointerException in OS X 10.9. Also tried it in Ubuntu 15.04 and cannot replicate the issue.

In Ubuntu with unity the full screen option maximizes the window and forces it on the foreground, but because the OS window controls are still enabled and visible I think it can confuse the users. For example, Alt+Tab shows the window switcher, but while in full screen only the Arduino window is displayed no matter what you select. If a new sketch is created the new window is opened in the background without a clear visual clue that a new sketch has indeed been opened, etc.

**Comment by damellis** [comment]
@tigoe I don't think we need a toolbar icon on Mac precisely because this full-screen mode is the new default behavior of the green maximize button. The Vimeo and YouTube players need a dedicated full-screen icon because they're not real windows and so they don't have a standard maximize button.

**Comment by carlosperate** [comment]
If this feature is to be implemented in a similar way in all platforms (there is no built-in full screen mode in most linux desktops nor windows), shouldn't the icon should stay for consistency?

**Comment by Lauszus** [comment]
This works as expected in Mac OS X 10.9.

@damellis note that before 10.10 their were a toolbar icon on Mac, so I think the best solution would be to only remove the toolbar icon when running 10.10 or any future versions.

**Comment by ffissore** [comment]
NullPointerException fixed pushed: @ArduinoBot will prepare another build.

This PR implements an old request: #1246
Indeed, time may have made it useless, and, if so, I'll be happy to just trash it.

I don't like having different GUIs (fullscreen button yes/no) for different OSs because that will cause troubles to tutorial and article writers.
I don't even like implementing conditionals on OSX versions: it's already quite hard to make three OSs work the same, introducing differences between versions of the same OS may only complicate things

**Comment by damellis** [comment]
@Lauszus good point about older versions of Mac OS X.
@ffissore personally, I think it's more important to be consistent with the platform (e.g. Mac or Windows) than have exactly the same behavior across platforms, especially for details like keyboard shortcuts and window management, although I realize it's probably a pain to implement. But this is probably a larger conversation and I don't want to give you a hard time about it. :)

**Comment by damellis** [comment]
Also, the new build seems to be working well. I couldn't get it to NPE any more.

**Comment by ffissore** [comment]
Don't get me wrong, but then I think the best way to stay consistent is to not implement fullscreen:
* we avoid different ui/behaviours on different OSs
* we avoid adding code (less code is less code that can break)
* we avoid glitches with unity on Ubuntu

**Comment by damellis** [comment]
One option would be to omit full-screen mode for other operating systems and just make the maximize button work as a full-screen button on Yosemite (OS X 10.10.3). This is the new OS X default (for most applications) but it requires some amount of changes to the code (on older software, the button still works as maximize not full-screen). 

Do other operating systems have a standard for this kind of full-screen mode? If not, then I agree that we don't necessarily need to add for them.

**Comment by ffissore** [comment]
Not that I know. Plus, the maximize button is handled by the window manager, not by the app. I don't think we can easily access that from java.
Does the IDE (plain 1.6.4) go fullscreen when you click the green dot?

**Comment by tigoe** [comment]
Yes.

t.

**Comment by ffissore** [comment]
Dropping PR: feature is native on macosx, causes troubles on other OSs

**Comment by damellis** [comment]
I don't see the same thing Tom does... for me, clicking the green button on 1.6.4 maximizes the window, it doesn't make it full-screen (on OS X 10.10.3, Yosemite). Something in this pull request changed the behavior so that the green button enters full-screen mode instead, as you'd expect with modern Mac apps. (I don't think you override the event handler on the button, you just have to configure the window to have the full-screen behavior instead of maximize, and the OS does the rest.) I still think this is worth doing.

**Comment by damellis** [comment]
I opened a separate, OS X-specific issue for this: https://github.com/arduino/Arduino/issues/3256

**Pull request closed without merging**
