### PR TITLE
Better error message when opening serial monitor on a busy serial device

### LINKED ISSUE #2632: 1.6 Windows: Java error when Serial opened by another instance
Open an IDE, start Serial monitor.
Open another IDE instance, try to upload to this port. Java errors will appear:

```
Sketch uses 7,140 bytes (24%) of program storage space. Maximum is 28,672 bytes.
Global variables use 363 bytes (35%) of dynamic memory, leaving 661 bytes for local variables. Maximum is 1,024 bytes.
Forcing reset using 1200bps open/close on port COM16
processing.app.debug.RunnerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(Unknown Source)
	at processing.app.debug.Compiler.upload(Unknown Source)
	at processing.app.Sketch.upload(Sketch.java:1218)
	at processing.app.Sketch.exportApplet(Sketch.java:1191)
	at processing.app.Sketch.exportApplet(Sketch.java:1163)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2391)
	at java.lang.Thread.run(Unknown Source)
Caused by: processing.app.SerialException: Error touching serial port 'COM16'.
	at processing.app.Serial.touchPort(Unknown Source)
	... 7 more
Caused by: jssc.SerialPortException: Port name - COM16; Method name - openPort(); Exception type - Port busy.
	at jssc.SerialPort.openPort(SerialPort.java:164)
	... 8 more
```

### PR DESCRIPTION
**Pull request by ffissore**
Closes #2632

@cmaglie @NicoHood

### CODE REVIEW

**Comment by NicoHood** [comment]
May i try this? Can you make the bot build it?

**Comment by ffissore** [comment]
Just wait a couple of hours

**Comment by ffissore** [comment]
@NicoHood have you a chance to test the fix?
Il giorno 12/feb/2015 12.45, "ArduinoBot" <notifications@github.com> ha
scritto:

**Comment by NicoHood** [comment]
yes, this weekend hopefully. For 16mhz I already tested it and it just works perfect. I just want to check 8mhz. But as I said, not sure if the older version supported this, so it would not matter anyways.

You know, this PR is just sitting here and waiting, waiting... and it just works fine. No need to discuss anything, I dont see anything that keeps you merging it. Just the 8mhz thing I just want to test first. Will post results then.

**Comment by NicoHood** [comment]
Yeah seems to work

**Pull request merged**
