### PR TITLE
Fix for #2969

### PR DESCRIPTION
**Pull request by agdl**

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Could you please give this commit a proper commit message, that describes what it does? Just referencing to an issue isn't very friendly wrt searching / scanning of the commit log, and makes the commit message useless if the issue list ever gets lost. If you want to refer to an issue, use the "Fixes #2969" syntax somewhere in the commit message body (i.e. not the first line), which will even cause github to autoclose the issue.

**Comment by bperrybap** [comment]
The new example code in the repo with address 8 looks ok, it might also be useful to update the actual web page here:
http://www.arduino.cc/en/Tutorial/MasterWriter
with a note indicating that i2c addresses 0-7 should be avoided as those are reserved.

**Comment by ffissore** [comment]
Indeed @agdl . This is not the first time. Hopefully it's the last

**Comment by bperrybap** [comment]
Huh? I'm now totally lost.
Is the Tutorial web page going to be updated to include a text note about not using reserved addresses 0-7?
Fixed examples is great but I think users should also be warned about using the reserved addresses in the descriptive text.

**Comment by agdl** [comment]
@bperrybap the on-line page take the code from git so it is automatically updated when the PR is merged. For the descriptive part i will add in all the on-line example the statement:

It is suggested to avoid addresses from 0 to 7 ok?

**Comment by bperrybap** [comment]
Cool. Very nice. Thank You.

**Comment by matthijskooijman** [comment]
Why is this closed?

**Comment by ffissore** [comment]
So @agdl can make another one, with a proper commit message, and a proper PR title and a proper PR description

**Pull request closed without merging**
