### PR TITLE
Fix conflict with declaration in std lib and gcc version > 4.9.2. See issue #4002

### PR DESCRIPTION
**Pull request by jlbirccyn**
See issue #4002

### CODE REVIEW

**Comment by jlbirccyn** [comment]
See issue #4002

**Comment by sandeepmistry** [comment]
@jlbirccyn thank you for submitting this!

I just tried it with ```gcc-arm-none-eabi-5_3-2016q1```, but get the following build error:

```
/Users/smistry/Documents/Arduino/hardware/arduino/sam/cores/arduino/itoa.c:124:14: error: conflicting types for 'utoa'
 extern char* utoa( unsigned long value, char *string, int radix )
              ^
In file included from /Users/smistry/Documents/Arduino/hardware/arduino/sam/cores/arduino/itoa.c:19:0:
/Users/smistry/Documents/Arduino/hardware/arduino/sam/cores/arduino/itoa.h:38:14: note: previous declaration of 'utoa' was here
 extern char* utoa( unsigned value, char *string, int radix ) ;
              ^
exit status 1
Error compiling for board Arduino Due (Programming Port).
```

Is there any reason why the equivalent change from ```itoa.h``` is not in ```itoa.c```?

**Comment by joshingyou** [comment]
Agree with @sandeepmistry just tried your change and got the same error about conflicting declaration of utoa

**Comment by cmaglie** [comment]
The latest newlib provides `itoa` too, also this function should be put under guards. Weird that the compiler doesn't throw errors on `itoa`, maybe because in this case the stub has the exact same signature as the lib function.

```
arm-none-eabi/include$ grep [iu]toa -r *
stdlib.h:char *	_EXFUN(__itoa,(int, char *, int));
stdlib.h:char *	_EXFUN(__utoa,(unsigned, char *, int));
stdlib.h:char *	_EXFUN(itoa,(int, char *, int));
stdlib.h:char *	_EXFUN(utoa,(unsigned, char *, int));
```

**Comment by cmaglie** [comment]
Fixed with #5480.
The implementation of `itoa` and `utoa` inside the Arduino core will be removed when the bundled arm-gcc will be upgraded.

**Pull request closed without merging**
