### PR TITLE
save output files

### PR DESCRIPTION
**Pull request by championswimmer**
@ffissore 

Recraeated the pull request

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by championswimmer** [comment]
@ffissore is this good to go to merge ?

**Comment by ffissore** [comment]
I think it is but I need another day before merging it

**Comment by championswimmer** [comment]
Umm bump ? :stuck_out_tongue:

**Comment by championswimmer** [comment]
@cmaglie Should I refactor this ?

**Comment by ffissore** [comment]
Working on this

**Comment by ffissore** [comment]
I've already rebased it, so I'm fine with the code

**Comment by ffissore** [comment]
Code rebased and merged. See https://github.com/arduino/Arduino/commits/4d029de000e2c696026ba8be074d395f7310daa5

**Pull request closed without merging**
