### PR TITLE
Timer1c support and per-variant initialization function

### PR DESCRIPTION
**Pull request by matthijskooijman**
These are two fairly unrelated improvements, other than that I need them both for a sleep timing improvement in our Pinoccio project.

The first commit adds support for timer 1c, on hardware that supports it. The second commit allows a variant file to supply a custom initialization function, to allow for board-specific code to be included by third parties.

@cmaglie, I'd be thankful if you could have a look at these soon and merge them if they look ok to you? I need these changes merged before I can publish some of my own Pinoccio work. Thanks!

### CODE REVIEW

**Comment by NicoHood** [comment]
Is there any documentation on how to actually use it? How do I have to name the file and where to place it?

**Comment by cmaglie** [comment]
Basically, if you define a function `void initVariant()` this function is called at init time before `void setup()`.
You can define this function anywhere but the intended place is inside your `variant/xxx` folder, typically in a file named `pins_arduino.c` that performs specific initialization required for the board (in addition to the `pins_arduino.h` that contains metadata about the board itself).

You can define ISR as usual, it's a C file that is compiled and linked like any other source file.

**Comment by vicatcu** [comment]
Nico,

I don't know how much documentation there is or where to find it, but take
a look at the core for WildFire here:
http://github.com/wickeddevice/wildfire-arduino-core for a working example
of using this functionality. The variant files are in
/WickedDevice/avr/variants/wildfirev3

Cheers,
Vic

Victor Aprea // Wicked Device
victor.aprea@wickeddevice.com
T: @vicatcu <http://twitter.com/vicatcu/>

**Comment by NicoHood** [comment]
Thank you so much!

Some results:
The cpp has to be placed in the same directory as the pins file (of course).
The cpp name doesnt matter.
You dont need a variants.h like in the example.
You dont need this initvariants function, you can also put other stuff in there, that gets compiled, like ISRs.

Thats my file for example: no_usb_isr.cpp
```cpp
#include <Arduino.h>
#include <pins_arduino.h>

// workaround for undefined USBCON has to be placed in every sketch
// otherwise the timings wont work correctly
ISR(USB_GEN_vect)
{
	UDINT = 0;
}
```

**Pull request merged**
