### PR TITLE
whats with the murge stuff

### PR DESCRIPTION
**Pull request by austinschlegel**

### CODE REVIEW

**Comment by NicoHood** [comment]
Whats this?

**Comment by PaulStoffregen** [comment]
> Whats this?

braceyourself

Ok, honestly I have no idea if they're preparing to release 1.6.6... just feeling like giving this silly meme generator a try.

**Comment by ffissore** [comment]
Ahahahah :)

**Comment by NicoHood** [comment]
very cool :D

**Comment by ffissore** [comment]
I think it's this one here https://github.com/arduino-libraries/Scheduler

**Comment by agdl** [comment]
Respect for @PaulStoffregen !

**Pull request closed without merging**
