### PR TITLE
Enable OTA Update mechanism for any mDNS enabled platform 

### PR DESCRIPTION
**Pull request by me-no-dev**
Adds ability to update the firmware of non-SSH boards using TXT
parameters from mDNS

Three new TXT keys are added (defaults are capital):
1. ssh_upload=YES/no
2. tcp_check=YES/no
3. auth_upload=yes/NO

* **"ssh_upload"** controls which Uploader should be used. Defaults to
SSHUploader
* **"tcp_check"** controls wether TCP reachability test should be performed.
Defaults to "yes". Boards that have few TCP ports available, can use
"no" to skip the check and update over UDP (ESP8266 for example).
* **"auth_upload"** controls wether authentication is required (only for
"ssh_upload=no").

One new pattern and two new variables are available.
1. Var **"network.port"** resolves to the advertised by mDNS device port.
2. Var **"network.password"** resolves to the entered device password if
upload authentication is used, else it's empty string.
3. Pattern **"upload.network_pattern"** is usable if the platform is using
different tool/command to do network updates. If not defined,
**"upload.pattern"** will be used instead.

Changes are inspired by the need of the ESP8266 Arduino project to utilize it's wireless for simple updates, it does not interfere with any other previous configuration or official Arduino boards and can be applied to basically any networked MCU.

### CODE REVIEW

**Comment by igrr** [comment]
Would really like to see this merged. Network upload stopped working for the esp8266 core since 88e8019 when `upload.via_ssh` property was removed.

**Comment by eliabieri** [comment]
👌🏻

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by me-no-dev** [comment]
OS X test went fine on both Yun and ESP8266

**Comment by me-no-dev** [comment]
Tested also on Windows XP 32, Windows 8.1 64 and Windows 10 Pro with success on all 3 OS's and both Arduino Yun and ESP8266

**Comment by brutzler** [comment]
Normaly working with Arduino IDE 1.6.5 and the last staging release: 1.6.5-1160-gef26c5f.
Unzipped the package into C:\temp. Started arduino.exe. After this I lost all data in (...appdata\roaming\arduino15\...). Somewhere between worried and pitted.....

**Comment by AdySan** [comment]
I get a prompt asking "Type board password to access its console", any idea what this password is?

**Comment by me-no-dev** [comment]
@AdySan Have you set a password ArduinoOTA.setPassword()?
If not, are you using the latest ESP8266 core from git? Updated OTA core is not yet published to the packager, so you need to manually clone the repository and use that.

**Comment by AdySan** [comment]
I've been using this build for OTA with NodeMCU 0.9 and works flawlessly. Now trying to program a ESP-201 (CH-PD -> 3.3V, GPIO15-> GND, Not sure what to do with GPIO0). I keep getting OTA_BEGIN_ERROR with the BasicOTA example. I noticed the same with an ESP-01 the other day, but it starter working later, not sure why. Any special tweaks needed for certain modules?

**Comment by AdySan** [comment]
I've been using this build for a few days with NodeMCU 0.9 hardware and it works flawlessly. Trying a ESP-201 today, I downloaded the BasicOTA example over serial. When I try to do an OTA download, I keep getting OTA_BEGIN_ERROR ([ERROR]: No response from device). I'm selecting Generic ESP8266 Module, Serial, 80MHz, 40MHz, DIO, 115200, 512K (64K SPIFFS), ck on 192.168.1.24

**Comment by krzychb** [comment]
Love hart you put into development of Arduino IDE and I am looking forward to seeing PR # 4107 merged :+1: 

keep calm and merge pr-4107 s

**Comment by reaper7** [comment]
@ArduinoBot - windows version on win10pro works for me perfectly!
@me-no-dev  good job - tnx!

**Comment by toyorg** [comment]
Win 10 Edu x64 with NodeMCU 1.0 works flawlessly. Thanks @me-no-dev

**Comment by me-no-dev** [comment]
@ffissore is there something wrong with the code? Or a reason to hold/reject this pull request?

**Comment by ffissore** [comment]
Lack of thorough testing on our side. Plus, @facchinm tried it for a few hours and it broke his dev env, so there are unhandled corner cases

**Comment by facchinm** [comment]
Really the bug I experienced was my fault, I've being testing this PR + my code for two weeks now and I haven't found any misbehaviour with original "upload using ssh" flow

**Comment by me-no-dev** [comment]
we had a similar case when the current IDE was not closed prior to installing/starting the PR Build, but I doubt any of that could be related as the code itself does not really touch anything that could cause a trouble.

**Comment by facchinm** [comment]
BTW, I'm :+1:  for merging this :wink:

**Comment by crushedice2000** [comment]
:+1:

**Comment by lmihalkovic** [comment]
[NTS]

**Comment by TurBoss** [comment]
:+1:

**Comment by TurBoss** [comment]
:+1:

**Comment by lmihalkovic** [comment]
[LMNTS]

**Comment by sticilface** [comment]
Please merge!

**Comment by facchinm** [comment]
No problem so far with this PR, had no time to test it directly but surely it doesn't harm the normal flow (ssh powered), so I'm going to merge it at last :smile:

**Comment by krzychb** [comment]
Hi Martino,

This is great!

If I were a woman I would give you a kiss
But I am not – so what about a hug?

Thank you for merging this pull request :smile: :+1:


Krzysztof

**Comment by reaper7** [comment]
:+1:
works for me on latest hourly_builds (16 December 2015 10:15:28 GMT) 
tnx!

**Comment by thegimliboy** [comment]
Thanks for merging :smile:

**Comment by mralexgray** [comment]
Hallelujah.

**Comment by mishoboss** [comment]
I just tried with today's build and I've got this:

[ERROR]: No response from device

Device is listed in the Network ports of Arduino IDE. I'm trying the "OTA-mDNS-SPIFFS.ino" example. Any ideas?

**Comment by krzychb** [comment]
Hi mishoboss - try this one - https://github.com/esp8266/Arduino/issues/1196#issue-121728848
This tread is now reserved to express or gratitude to Martino :smile:
Krzysztof

**Comment by me-no-dev** [comment]
kinda sad it did not make it into 1.6.7 :(

**Comment by facchinm** [comment]
It made it into 1.6.7 at the end :wink:

**Comment by me-no-dev** [comment]
Oh my god! Thanks! Did not mean to rant, but was so not looking forward troubleshooting users another release cycle :)

**Comment by g0ro** [comment]
@ArduinoBot build this please

**Comment by facchinm** [comment]
@g0ro, the patch is already included in IDE 1.6.7+, no need to trigger a bot build

**Comment by sypumsb** [comment]
@ArduinoBot build this again, or give new link. I have several reasons to stay on the old version. Please.

**Comment by artynet** [comment]
would you mind writing the exact syntax to customise the boards.txt file ? plese be more specific....

I have tried so far :
```
myBoard.tcp.ssh_upload=no  
myBoard.tcp.tcp_check=no  
myBoard.tcp.auth_upload=no

myBoard.network.ssh_upload=no  
myBoard.network.tcp_check=no  
myBoard.network.auth_upload=no 

myBoard.port.ssh_upload=no  
myBoard.port.tcp_check=no  
myBoard.port.auth_upload=no  
```
these three combinations without any result...

**Comment by me-no-dev** [comment]
@artynet properties are given through mDNS, not through boards config.

**Pull request merged**
