### PR TITLE
A new compiler

### PR DESCRIPTION
**Pull request by ffissore**
This PR replaces previous Compiler java class (now renamed OldCompiler) with a new, almost empty one, which delegates all the work to a command line tool, named `arduino-builder`, which will do the actual compilation

This replaces #2729 and solves many issues: see https://github.com/arduino/Arduino/labels/Component%3A%20Preprocessor

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Is the source for this tool available anywhere?

**Comment by NicoHood** [comment]
https://github.com/arduino/arduino-builder

Also consider to add this then:
https://github.com/arduino/Arduino/pull/3697
https://github.com/arduino/Arduino/pull/3757

**Comment by ffissore** [comment]
@NicoHood we'll implement those two additional features later. Being this new thing a replacement of an old but well known other thing, we must first be sure we are not introducing regressions before we add new features

**Comment by lmihalkovic** [comment]
[NTS]

**Pull request merged**
