### PR TITLE
Simplify some examples

### PR DESCRIPTION
**Pull request by ComputerNerd**
I noticed that some of the examples could have been written in a more concise way. This made them easier to read and shorter.

The general trend that I noticed was this:
```
if(variable==HIGH)
    digitalWrite(pin,HIGH);
else
   digitalWrite(pin,LOW);
```

Why not just do this instead:
```
digitalWrite(pin,variable);
```

### CODE REVIEW

**Comment by Avamander** [comment]
I think the ^= and ! should be explained then.

**Comment by agdl** [comment]
@Avamander the examples are intended for people who want to understand programming and are written in the easiest as possible for this reason, so I'm sorry but this PR won't be merged..

**Comment by Avamander** [comment]
FYI: Not my pull request.

**Comment by cmaglie** [comment]
These examples are for absolute beginners and the "compact" version adds complexity (even more using `^=` that introduce two new concepts in a row: the XOR and the compound assignment).

@tigoe @SimonePDA @shfitz
should we clarify this is in a FAQ? This is the 3rd PR this month that tries to improve the examples, maybe we should think about a reorganization of the base examples and add a "contribution guidelines".

**Comment by agdl** [comment]
@Avamander  sorrywrog tag, it was for @ComputerNerd

**Comment by per1234** [comment]
>add a "contribution guidelines".

See https://github.com/arduino/Arduino/issues/3368

**Comment by tigoe** [comment]
@cmaglie, yes I agree, a FAQ would be good. We have this: https://www.arduino.cc/en/Reference/StyleGuide  Which you could add do and/or make more prominent.

**Comment by ComputerNerd** [comment]
@cmaglie Is it just the XOR compound assignment that you object to? It could also be written as
```
ledState = !ledState;
```
 If you like the other changes I could rebase my commit to not use the XOR compound assignment and use either the above alternative or bring back the if statements.

**Comment by tigoe** [comment]
Me personally, I'd leave all the logical operators out of this example and introduce them later. For someone who's seeing their first if() statement, that's enough to deal with. Conciseness is less a priority for these examples than illustrating one clear concept per example.

If you want to write some examples that illustrate and explain the logical operators, though, I think that'd be great.

**Pull request closed without merging**
