### PR TITLE
Allow library manager to install multiple libraries at once.

### PR DESCRIPTION
**Pull request by Lauszus**
I just selected comma as the delimiter, but if you prefer something else I can change it.

### CODE REVIEW

**Comment by Lauszus** [comment]
Btw you might want to see the diff while ignoring whitespace: https://github.com/arduino/Arduino/pull/2947/files?w=1

**Comment by ffissore** [comment]
super fast :)

**Comment by ffissore** [comment]
I'm just changing error messages so that they mention, for example, which library is already installed

**Comment by ffissore** [comment]
Ah sorry you did that already in #2948

**Comment by ffissore** [comment]
Thanks!

**Comment by Lauszus** [comment]
You are welcome :)

Btw the reason why I wanted this was for the Balanduino: https://github.com/tkjelectronics/Balanduino, as this will allow me to write an install script that installs all required libraries and the hardware add-on. This should make it much easier for newcomers to the Arduino scene.

**Pull request merged**
