### PR TITLE
Minor change to example sketch comment

### PR DESCRIPTION
**Pull request by pfeerick**
Can't be the right word! ;)

### CODE REVIEW

**Comment by rkost** [comment]
I think 'can' is the right word here. You need to read it as conclusion. The number is to big than to store it to an integer variable. One may say '... so it is not possible to store in an int' or something like this

**Comment by facchinm** [comment]
Wording is correct indeed :smile:

**Comment by pfeerick** [comment]
@rkost Indeed... hence why I removed the 't... as it was originally "can't" ...  as "become a bigger number than can not be stored in an int" makes no grammatical sense! @facchinm might want to come back at apply this at some point ;)

**Comment by facchinm** [comment]
Err, it turned out that in Italy we have some problems with double negatives :smile: 
After a discussion with the best linguists it turned out that you are right, so I'm merging this :wink: Sorry for closing too soon

**Comment by pfeerick** [comment]
No worries... I probably didn't help with my joke about "can't"... I did the assume thing, thinking the commit would speak for itself... 😵

**Pull request merged**
