### PR TITLE
RFC > Compiler: core files in "core" subfolder, libraries in "libraries"

### PR DESCRIPTION
**Pull request by ffissore**
With this PR, temporary build folder no longer gather all object files in one folder, flat. Core object files go to "core" folder, libraries to "libraries" (note: libraries already went to a folder name after the library name; I've added an additional folder level because it seemed more tidy **to me**

/cc @NicoHood @matthijskooijman @PaulStoffregen @cmaglie @facchinm

### CODE REVIEW

**Comment by ffissore** [comment]
Please note this ugly line
https://github.com/arduino/Arduino/pull/3303/files#diff-9cd90eab2dcf151a63c144aff0e043b9R1149
It's needed becase SAM platform.txt hardcodes a file path: `{build.path}/syscalls_sam3.c.o`

**Comment by ffissore** [comment]
Please give this PR a try using your cores

**Comment by NicoHood** [comment]
What issue are you referring to? That the .ino file should not be names as a .cpp/.h file?

**Comment by matthijskooijman** [comment]
Would it make sense to also have "sketch" folder and compiler the sketch in there? That would prevent problems when the sketch contains a subdirectory called "core" for example when fixing #3080 later.

**Comment by ffissore** [comment]
:+1:

**Comment by ffissore** [comment]
This latest build is the result of a force push: I've removed the java hardcoded replacement of that `{build.path}/syscalls_sam3.c.o` using `platform.keys.rewrite.txt` and I've put sketch sources and object files into `sketch` folder

**Pull request merged**
