### PR TITLE
Enhance readme for readability

### PR DESCRIPTION
**Pull request by TheKnarf**
- Adding Arduino logo from website as a part of the Readme

- Making links easier to read by using link names instead of showing the whole link

### CODE REVIEW

**Comment by TheKnarf** [comment]
The `PR Quality Review` is complaining about `[list-item-indent] Incorrect list-item indent: add 2 spaces`, but I have no idea how to fix it. I've tried force pushing a few changes to try and see if I could figure it out, but it doesn't fix it.

Still; I think this is an improvement over how the Readme currently looks.

**Comment by facchinm** [comment]
@per1234 what do you think about this?

**Comment by per1234** [comment]
It looks good to me. I'm always partial to bulleted lists.

I would prefer the logo to be a bit smaller, since it pushes the useful information in the readme quite a way down the page, but maybe others like the big and bold logo.

I don't know what the situation is with the Codacy check failure. I have always used a single space to separate the bullet character from the text in Markdown lists and it seems the attempt to fix the failure by adding an extra space in the force push still didn't resolve the failure.

**Comment by facchinm** [comment]
I'm going to merge it then; we can make the logo smaller in another commit if needed

**Pull request merged**
