### PR TITLE
Annotate custom menu to avoid name clashing

### LINKED ISSUE #5260: Custom menu selection text doesn't update after changing boards when menu ID is different but menu text is the same as a previously selected board
Using Arduino IDE 1.6.11 Hourly Build 2016/08/16 11:33 with Windows 7 64 bit
1. File > Preferences > Additional Boards Manager URLs: > https://zevero.github.io/avr_boot/package_zevero_avr_boot_index.json
1. Tools > Board > Boards Manager > avr_boot > 1.2.0 > Install > Close
1. Tools > Board > Arduino/Genuino Mega or Mega 2560
1. Tools > Board > ATmega328/P

Now look at the selection text shown in quotes next to the **Tools > Board > Processor** menu item: `Processor: ATmega2560 (Mega 2560)`. I you select the **Tools > Board > Processor** menu you can see that it doesn't have an `ATmega2560 (Mega 2560)` option. That text has been left over from the previous board selection. Even after changing the Processor menu selection the menu item text doesn't change.
clipboard02

This only occurs when the menu ID value in boards.txt is different from the Arduino AVR Boards(or any other core) value but the menu text value in boards.txt is the same as the other core's value. In this [case](https://github.com/zevero/avr_boot/blob/gh-pages/avr/boards.txt#L8):

```
menu.processor=Processor
```

If this is changed to `menu.cpu=Processor`(the [same ](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/boards.txt#L3)as Arduino AVR Boards) then the issue doesn't occur.

If it's changed to `menu.processor=CPU` then the issue doesn't occur.

If it's changed to `menu.avr_boot_processor=Processor` the issue does occur.

EDIT 2017-07-06: I checked with Arduino IDE 1.8.3 and the issue still occurs after following the steps above..

### PR DESCRIPTION
**Pull request by facchinm**
Fixes #5260

@per1234 @hasenradball  can you test in your environment too? Thanks!

### CODE REVIEW

**Comment by hasenradball** [comment]
@facchinm Hi just replace the java file in my Arduino path?

**Comment by facchinm** [comment]
You can grab the right package for your OS, unzip it and run arduino executable from there.

**Comment by per1234** [comment]
@facchinm using test build 854, I can no longer reproduce the problem with the "Upload Speed" menu of the ESP32 and ESP8266 cores. However, I can still reproduce the original issue with the "Processor" menu of Arduino AVR Boards' Arduino Mega and Mega 2560 and avr_boot's ATmega328/P boards:
Clipboard02
I haven't been able to figure out why one was fixed and the other not fixed.

**Comment by facchinm** [comment]
@per1234 thanks a lot for testing, I'm taking a look immediately

**Comment by facchinm** [comment]
I pushed a new commit, tested against the original bug and seems to fix it. However that piece of code is really a nightmare and should be refactored by someone who knows Swing sooner or later.

**Comment by hasenradball** [comment]
Hi 
Upload issue is fixed nothing to complain from my side.
Thank you!

**Comment by per1234** [comment]
@facchinm still the same problem with the "Processor" menu of Arduino AVR Boards' "Arduino Mega and Mega 2560" and avr_boot's "ATmega328/P" boards for me using build 857.

I notice that if the "Arduino Mega and Mega 2560" board is selected when I start the Arduino IDE and I then select **Tools > Board > ATmega328/P**, the problem does not occur. I need to select **Tools > Board > Arduino Mega and Mega 2560** (even if it was already selected) before selecting **Tools > Board > ATmega328/P** to reproduce the bug.

**Comment by hasenradball** [comment]
Maybe it is a good Idea to do the rework of the code. So if code grows over time without having a good architecture a rework would be the the best. Also if it is hard work or a hard job the result will be a mor structured code.
😉

**Comment by per1234** [comment]
The issue no longer occurs for me using build 858. Great work @facchinm!

**Pull request merged**
