### PR TITLE
Symlink the arduino binary

### PR DESCRIPTION
**Pull request by 2E0PGS**
install.sh should symlink arduino into `/usr/local/bin/arduino` so arduino is accessible via users PATH.

Related issues:

https://github.com/arduino/Arduino/issues/5780

https://github.com/arduino/Arduino/issues/5366

### CODE REVIEW

**Comment by facchinm** [comment]
@2E0PGS this would make the "installation" dependant on `sudo`, which I would avoid at all costs.
Maybe checking the UID and then symlinking the executable in `/usr/local/bin/` if we have permissions to do it could be a good solution.
This way, launching `./install.sh` as a user wouldn't install the symlink, while `sudo ./install.sh` would.

**Comment by 2E0PGS** [comment]
./install.sh would prompt for a password once it hits the symlink part if ran as non root currently.


⁣Peter Stevenson (2E0PGS)
http://www.m3pgs.co.uk​

**Comment by 2E0PGS** [comment]
OK I suppose I assumed they are in the SUDOers group. Ref want to access it from CLI I think most who install software expect to find it in path. Thats the easy way to launch software besides using menu entries.

How about making the whole script require root level privileges and then I add code to move the folder into /opt/ and generate symlink to usr/bin. That to me seems like a more sensible trend of installers.

Could add flags for user level install and system wide installs. one requiring root and one not.

**Comment by 2E0PGS** [comment]
Yea that's a good idea.

**Comment by 2E0PGS** [comment]
I will add the changes ASAP.

**Comment by 2E0PGS** [comment]
Added the suggested changes.

**Comment by 2E0PGS** [comment]
Did anything like this ever get implemented? I am about to install Arduino and this pull never got merged so wonder if I need to manually symlink still...

**Comment by 2E0PGS** [comment]
I did indeed have to symlink it manually still or use my branch. 

I think this is fine for merge if the error message from `rm` or `ln` is ok in addition to the custom one. Otherwise I will need to modify this pull request so it only shows our custom error message if they don't run using sudo.

**Pull request merged**
