### PR TITLE
DO NOT MERGE: testing arduino-builder with multi core support

### PR DESCRIPTION
**Pull request by ffissore**
This build (the one @ArduinoBot will kindly provide) contains a version of arduino-builder which will leverage all your PC cores to speed up compilation. Rough measurements show a speed improvement of 30%, but your mileage may vary

Please post your :+1: if you find it works as expected

### CODE REVIEW

**Comment by NicoHood** [comment]
Have you triggered the bot or is it just busy?

**Comment by NicoHood** [comment]
I compiled it myself. It seems to work and speed up the process. All 8 cores are used. (Elementary > Ubuntu LTS 64 bit)

Now I am looking forward to make this usable with raspi2. This would be an ultimate combination of the two boards. Also Processing is now supported on the pi where you can combine the Arduino even better with the pi. Serial, gpios or whatever. But thats another issue/feature ;)

**Comment by ffissore** [comment]
Thank for the test @NicoHood I'm looking forward for some windows and mac users

**Comment by PaoloP74** [comment]
Windows 7 - Intel core i5 with SSD
Sketch Blink
Latest Hourly build (3 Dec - 9:59) 7.0 sec.
This build (PR 4240) 4.8 sec.
Second compilation 2.8 sec both.

**Comment by NicoHood** [comment]
The build does not seem to mark compile errors properly. Just hit into errors witht his (leonardo):
```cpp
uint8_t array[2048];

void setup()
{
  Serial.begin(115200);
  memset(0xFF, array, sizeof(array);
}

void loop()
{
  for (size_t i = 0; i < sizeof(array); i++)
  {
    Serial.println(array[i], HEX);
  }
}
```

**Comment by ffissore** [comment]
Indeed. A previous version was eating errors printed on stderr. Please download the latest build and retry

**Comment by NicoHood** [comment]
Works now. It seems you used a commit --amend and forced a push. Please do not do that next time ;)

**Comment by matthijskooijman** [comment]
> Works now. It seems you used a commit --amend and forced a push. Please do not do that next time ;)

I do that with pullrequests all the time, as far as I'm concerned, it's up to people pulling PR branches to be careful while pulling.

**Comment by MauroMombelli** [comment]
used time + command line forcing arduino uno as board to get better result
arch linux, gcc 5.2
nightly: 
arduino --verify ./examples/01.Basics/Blink/Blink.ino --board arduino:avr:uno  5.98s user 0.34s system 222% cpu 2.847 total

PR-4240:
arduino --verify ./examples/01.Basics/Blink/Blink.ino --board arduino:avr:uno  6.17s user 0.25s system 227% cpu 2.823 total

**Comment by ffissore** [comment]
@NicoHood indeed I often rebase and force push on my dev branches, in order to keep the history nice and clean
@MauroMombelli it looks like this PR has worsen the situation. However you used the "arduino" command, which starts the whole IDE, adding much noise to your measurement. Plus, FYI, this PR makes a sensible difference only when compiling for the first time: on the second run, most of the needed files (especially those from core and from libraries) will be already compiled and thus skipped.
Anyway, the fact that you were able to compile is a good feedback. Thank you

**Comment by PaoloP74** [comment]
Sketch ASCIITable
Nightly 7.4 sec
Multi-core 3.9 sec

**Comment by MauroMombelli** [comment]
@ffissore compiled a bigger sketch, it take about 6 seconds to compile (and because arduino command take ~6 seconds, any noticeable gain should cover the noise), the situation is not worse because running many time the build command (deleting the /tmp/build* folder) give a variatio of about +-1 seconds.

A script can be made to measure to collect many run and see if there is a meaningful difference between the two script. Still better than using "feeling", also difference can be caused by different load on the system

target is atmega2560, code is BCN3D_v3_0_2x01 (download: https://github.com/BCN3D/BCN3D-Firmware/tree/master/BCN3D%2B/BCN3D_v3_0_2x01)

nightly:
Global variables use 4,810 bytes (58%) of dynamic memory, leaving 3,382 bytes for local variables. Maximum is 8,192 bytes.
arduino --verify ~/Arduino/BCN3D_v3_0_2x01/BCN3D_v3_0_2x01.ino  12.67s user 0.70s system 117% cpu 11.333 total

PR4240:
Global variables use 4,810 bytes (58%) of dynamic memory, leaving 3,382 bytes for local variables. Maximum is 8,192 bytes.
arduino --verify ~/Arduino/BCN3D_v3_0_2x01/BCN3D_v3_0_2x01.ino  12.67s user 0.67s system 118% cpu 11.267 total

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by andig** [comment]
Is there any progress? Milestone is 1.6.8 but apparently it's not merged? Would love to speed up the build using the esp8266 core/libs. What is missing?

**Comment by facchinm** [comment]
Available in 1.9.0 Beta builds, closing this one

**Pull request closed without merging**
