### PR TITLE
Move AVR Wire library utility folder under src

### LINKED ISSUE #4653: Library can't use both 'src' and 'utility' folders.
Hi,

with latest nightly build i get this error:

Library can't use both 'src' and 'utility' folders. Double check C:\Documents and Settings\Test\Desktop\arduino-1.6.8\hardware\arduino\avr\libraries\Wire

The latest nightly build that was tested and was working 19.02.2016.

Thanx

### PR DESCRIPTION
**Pull request by sandeepmistry**
Resolves #4653.

### CODE REVIEW

**Comment by jpl-pfungst** [comment]
Hello,

I have downloaded the file for Windows, I have unpack the zip file,
replace the original arduino library
restarted the test and get the same error.

in the source file
#include <stdio.h>
#include <VirtualWire.h>
#include <Servo.h>

having only one include works with both it does not.

Thanks for your help

<--------------------------------------------------------------------------------------------------
Arduino: 1.6.8 (Windows 10), Board: "Arduino/Genuino Uno"

libraries\Servo\avr\Servo.cpp.o: In function `__vector_11':

C:\Program Files (x86)\Arduino\libraries\Servo\src\avr/Servo.cpp:81: 
multiple definition of `__vector_11'

libraries\VirtualWire\VirtualWire.cpp.o:C:\Program Files 
(x86)\Arduino\libraries\VirtualWire/VirtualWire.cpp:591: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Fehler beim Kompilieren.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
 >--------------------------------------------------------------------
Am 04.03.2016 um 23:31 schrieb Arduino Bot:
> :white_check_mark: Build completed.
>
> Please test this code using one of the following:
>
> :arrow_down: http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-4655-BUILD-518-linux32.tar.xz
> :arrow_down: http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-4655-BUILD-518-linux64.tar.xz
> :arrow_down: http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-4655-BUILD-518-windows.zip
> :arrow_down: http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-4655-BUILD-518-macosx.zip
> :arrow_down: http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-4655-BUILD-518-linuxarm.tar.xz
>
> :information_source: The `linuxarm` build is still experimental and may not be always available.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/arduino/Arduino/pull/4655#issuecomment-192501656

-- 
Jean-Pierre Lauqué
Zwingenbergerstr. 9
D64319 Pfungstadt
jean-pierre@lauque.de
Fix 00496157990844
Mob 0049170 4852635

**Comment by jpl-pfungst** [comment]
what do you mean ?
What is the AVR wire library?
what the full path ?
I got :  arduino\hardware\arduino\avr
\bootloaders
\cores
\frimwares
\libraries\
...
\Wire
\examples
     \src
     \utility
          twi.c
          twi.h
     wire.cpp
     wire.h

\variants
----------------------------
what do I have to move where?

**Comment by sandeepmistry** [comment]
@jpl-pfungst please see @PaulStoffregen's comment in https://github.com/arduino/Arduino/issues/4654#issuecomment-192503371.

The goal of this patch is to resolve issue #4653, that occurs with the hourly build.

**Comment by MauroMombelli** [comment]
this patch is fine, but the motivation it is needed are scary; all libraries using "utility" folder (pre-1.6) which is seen as flat, will NOT work now.

**Comment by matthijskooijman** [comment]
@MauroMombelli, I'm not sure I see your point here? The flat type of libraries, as was the default in 1.0, do not have any `src` folder, just source files in the root and optionally in a `utility` folder. Those libraries should work just as they did before. The problem with the Wire library, AFAICS, is that it was converted from a flat to recursive style library incorrectly: The source files from the root were moved into the src/ folder, but not the utility folder, so the resulting library didn't work under *any* Arduino version. Or am I missing your point here?

**Comment by MauroMombelli** [comment]
no you are right, i missed the src

**Pull request merged**
