### PR TITLE
Added Multicast UDP support

### PR DESCRIPTION
**Pull request by aallan**
Patch to add multicast UDP support to the current Arduino Ethernet library.

### CODE REVIEW

**Comment by roeften** [comment]
This patch works for me. I've written an example here:
http://blog.roeften.com/2015/03/multicast-communications-between.html

**Comment by subnoize** [comment]
Well, after two years, what is the hold up with this?

**Comment by cmaglie** [comment]
Rebased and merged.
I've changed the method name from `beginMulti` to `beginMulticast` to be more Arduino-style, hope this won't be a big concern.

Thanks you and sorry for the long delay.

**Comment by subnoize** [comment]
Cool! Thank you!

**Pull request closed without merging**
