### PR TITLE
Save windows position when closed with Alt+F4 or "X" button

### LINKED ISSUE #4404: Remember window positions
When Arduino starts, it alway opens in a small window rather than remembering the window positions that were last used.  Please add a feature to remember the last window positions. 

Here's an example with the arduino window stretched to take up 3/4ths of the screen starting at the left side of the screen and then the Serial Monitor on the right 1/4 of the screen.  
capture

### PR DESCRIPTION
**Pull request by cmaglie**
/cc @willie68 @doby162 @PickyBiker

should fix #4404 #4218

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Commits look good to me.

**Comment by PickyBiker** [comment]
This works well for me.  It saves a lot of time repetitively resizing and locating windows. Thank you for implementing it.

 

Mike

**Comment by PickyBiker** [comment]
This fix works well for me. It saves a lot of time repetitively resizing and positioning windows. Thank you for implementing this fix.

 

Mike

**Comment by PickyBiker** [comment]
I just noticed that if I start by clicking on Arduino.exe it works well.  I associated .ino files with Arduino.exe. If I then start it by clicking on an .ino file, it starts arduino.exe but it doesn't remember the last window position.

**Comment by PickyBiker** [comment]
The windows version gets an error when it runs:

**Comment by PickyBiker** [comment]
Here is the error
error

**Comment by cmaglie** [comment]
Hi @PickyBiker,
I've just checked the build and it starts without problems, may you check the downloaded file (it should be154848694 bytes long) and the unzipped folder to see if it contains a "java" subfolder?

**Comment by PickyBiker** [comment]
Okay, I re-downloaded the file and it worked this time.

 

Now it remember the window position whether I start it with Arduino or the .ino file.

 

Nice job, thank you very much. I'm sure others will like this as well.

 

As a further thank you, I am going to donate $50 when I download the released 1.68 version.

 

Once again, thank you!

**Comment by willie68** [comment]
Great, working.

**Pull request merged**
