### PR TITLE
Some i18n/text fixes

### PR DESCRIPTION
**Pull request by hasso**
Some fixes for a problems found in progress to update a translation.

### CODE REVIEW

**Comment by kotobuki** [comment]
As a translator (Japanese), these fixes should be really helpful.

**Comment by matthijskooijman** [comment]
Commits look good to me. I added some minor remarks, would be good to have them fixed (you can edit commits using interactive rebase and then force push to the same branch on github to replace the commits in this PR).

**Comment by hasso** [comment]
Thanks for comments, should be fixed now.

**Comment by cmaglie** [comment]
Thank you!

**Pull request merged**
