### PR TITLE
Compilation cleanup and automatic library dependencies

### PR DESCRIPTION
**Pull request by matthijskooijman**
This pullrequest is based on and replaces #1726. While rebasing that PR I also moved some code around for a more sensible structure, which again exposed some opportunities for cleanup, meaning this pullrequest now moves a lot of code around, while only the last commit actually changes the detection of dependencies.

The other commits move and clean up code, which does improve consistency in a few places, fixing a few bugs as a side effect.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
The library dependency part of this PR is more elegantly solved by #2792. Some of the cleanups have been included in the IDE refactor from a while ago, and the rest is probably broken by that. However, some cleanups might still be useful, so I'll have to go over this PR soon and salvage the useful parts.

**Comment by ffissore** [comment]
@matthijskooijman we did a lot of work since this PR, including library dependencies. Are there any part of it which could go to a separate PR?

**Comment by cmaglie** [comment]
IMHO the only commit that is still worth merging (or cherry-picking) is

8bece7c - Simplify Sketch.load

(Sketch.load is now in SketchData.load)

All the rest (AFAICS) have been already merged or implemented in another way.

**Comment by matthijskooijman** [comment]
I haven't looked very closely at the current compilation code (after the refactoring done earlier and the introduction of arduino-builder), so I'm not sure what is still relevant (IIRC some of these commits were already merged manually as part of that refactoring as well). I won't have time soon to rebase that one commit, so perhaps @cmaglie or @ffissore could pick it up directly?

**Comment by matthijskooijman** [comment]
The changes in the "Simplify Sketch.load" commit have been included as part of another commit in #4363, and all the other commits in this PR are either included, or no longer relevant with arduino-builder, so I'm closing this one.

**Pull request closed without merging**
