### PR TITLE
IDE 1.6.11 release candidate

### PR DESCRIPTION
**Pull request by cmaglie**
This is a possible RC for the IDE 1.6.11.
We have made a bunch of fix that we will release next week.

- Bugfix: package_index.json tools handling for 3rd party urls.
- Bugfix: #include "..." of sketch files in subfolder.
- Reverted avrdude to 6.0.1 until all bugs are fixed.

### CODE REVIEW

**Comment by facchinm** [comment]
Signed packages (release style) will be available soon at:

:arrow_down: http://downloads.arduino.cc/ide_staging/arduino-1.6.11-windows.zip
:arrow_down: http://downloads.arduino.cc/ide_staging/arduino-1.6.11-windows.exe

:arrow_down: http://downloads.arduino.cc/ide_staging/arduino-1.6.11-macosx-signed.zip

:arrow_down: http://downloads.arduino.cc/ide_staging/arduino-1.6.11-linux32.tar.xz
:arrow_down: http://downloads.arduino.cc/ide_staging/arduino-1.6.11-linux64.tar.xz
:arrow_down: http://downloads.arduino.cc/ide_staging/arduino-1.6.11-linuxarm.tar.xz

**Comment by Breidenbach** [comment]
Got the following:

Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 4,254 bytes (13%) of program storage space. Maximum is 32,256 bytes.
Global variables use 475 bytes (23%) of dynamic memory, leaving 1,573 bytes for local variables. Maximum is 2,048 bytes.
{runtime.tools.avrdude.path}/bin/avrdude -C{runtime.tools.avrdude.path}/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:i 
java.io.IOException: Cannot run program "{runtime.tools.avrdude.path}/bin/avrdude": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:11)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:130)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:209)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.Sketch.upload(Sketch.java:1187)
	at processing.app.Sketch.exportApplet(Sketch.java:1160)
	at processing.app.Sketch.exportApplet(Sketch.java:1132)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2409)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Breidenbach** [comment]
Compiling ArduinoISP:

Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 4,254 bytes (13%) of program storage space. Maximum is 32,256 bytes.
Global variables use 475 bytes (23%) of dynamic memory, leaving 1,573 bytes for local variables. Maximum is 2,048 bytes.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 4.4
         Vtarget         : 0.3 V
         Varef           : 0.3 V
         Oscillator      : 28.800 kHz
         SCK period      : 3.3 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file "/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex"
avrdude: writing flash (4254 bytes):

Writing | ################################################## | 100% 0.82s

avrdude: 4254 bytes of flash written
avrdude: verifying flash memory against /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:
avrdude: load data flash data from input file /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:
avrdude: input file /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex contains 4254 bytes
avrdude: reading on-chip flash data:

Reading | #########################################avrdude: stk500_recv(): programmer is not responding
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by matthijskooijman** [comment]
@Breidenbach, does this occur every time, or just once? Does the exact same setup work with 1.6.9 (rechecking would be useful). It looks a bit like a one-off connection problem to me.

**Comment by Breidenbach** [comment]
1.6.9 results:  All is well!


Sketch uses 5,108 bytes (15%) of program storage space. Maximum is 32,256 bytes.
Global variables use 475 bytes (23%) of dynamic memory, leaving 1,573 bytes for local variables. Maximum is 2,048 bytes.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 4.4
         Vtarget         : 0.3 V
         Varef           : 0.3 V
         Oscillator      : 28.800 kHz
         SCK period      : 3.3 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file "/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex"
avrdude: writing flash (5108 bytes):

Writing | ################################################## | 100% 0.94s

avrdude: 5108 bytes of flash written
avrdude: verifying flash memory against /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:
avrdude: load data flash data from input file /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:
avrdude: input file /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex contains 5108 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.74s

avrdude: verifying ...
avrdude: 5108 bytes of flash verified

avrdude done.  Thank you.

**Comment by cmaglie** [comment]
@Breidenbach thanks for the feedback!

It's really weird, from your log it seems that avrdude has correctly programmed the board and failed in the middle of the verification, my feeling is that this is really a one-off connection problem as @matthijskooijman said.

Can you confirm that you can consistently reproduce the error?

I'm asking because:
- I've just tested on MacOSX and I can upload the ArduinoISP sketch successfully on the Uno board.
- avrdude in this build is **exactly** the same as in the IDE 1.6.9 (version 6.0.1 same build) so it should work (or not work :-)) exactly the same as in IDE 1.6.9.

**Comment by Breidenbach** [comment]
I downloaded a new copy of 1.6.11 and ran it.  Computer has been rebooted several times since the last use.  Arduino has been powered down also.  Got the following:

Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 4,254 bytes (13%) of program storage space. Maximum is 32,256 bytes.
Global variables use 475 bytes (23%) of dynamic memory, leaving 1,573 bytes for local variables. Maximum is 2,048 bytes.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 4.4
         Vtarget         : 0.3 V
         Varef           : 0.3 V
         Oscillator      : 28.800 kHz
         SCK period      : 3.3 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x1e950f
avrdude: reading input file "/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex"
avrdude: writing flash (4254 bytes):

Writing | ################################################## | 100% 0.83s

avrdude: 4254 bytes of flash written
avrdude: verifying flash memory against /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:
avrdude: load data flash data from input file /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:
avrdude: input file /var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex contains 4254 bytes
avrdude: reading on-chip flash data:

Reading | ######################################avrdude: stk500_recv(): programmer is not responding
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by matthijskooijman** [comment]
Did you re-upload the Arduino-as-ISP sketch to the programmer Arduino when switching between 1.6.9 and 1.6.11? If so, could you upload the sketch using 1.6.9 and then try upload using programmer on 1.6.11?

**Comment by matthijskooijman** [comment]
(deleted previous comment, I thought you were using ArduinoISP)

Does uploading another sketch (e.g. empty sketch) work?

**Comment by cmaglie** [comment]
> Reading | ######################################avrdude: stk500_recv(): programmer is not responding
> Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

never seen a similar error in my life...

I see also a small difference in the compiled sketch, your ArduinoISP is 4254 bytes instead on my mac I get 4380.

@Breidenbach 
- The sketch is the ArduinoISP from the example menu?
- May you try to run the avrdude command line from terminal? (just copy and paste the line `/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/build684126979c9a3c00e8bd9f40425b84de.tmp/ArduinoISP.ino.hex:i` from the IDE console into the terminal)
- May you post the content of the result ArduinoISP.ino.hex in a [gist](https://gist.github.com/)?

**Comment by Breidenbach** [comment]
This from uploading example Blink (I’ll try the command line next)

  Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 928 bytes (2%) of program storage space. Maximum is 32,256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2,039 bytes for local variables. Maximum is 2,048 bytes.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/buildd5ae82e677127ac286f51de66781d807.tmp/Blink.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 4.4
         Vtarget         : 0.3 V
         Varef           : 0.3 V
         Oscillator      : 28.800 kHz
         SCK period      : 3.3 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: reading input file "/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/buildd5ae82e677127ac286f51de66781d807.tmp/Blink.ino.hex"
avrdude: writing flash (928 bytes):

Writing | ###########################################avrdude: stk500_recv(): programmer is not responding
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Breidenbach** [comment]
I recompiled the ArduinoISP I have, which indeed is slightly different from the one in Examples, and tried to upload it from the console - this is the result.  I also tried to use the version from Examples and it failed in the same way.


avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 4.4
avrdude: stk500_recv(): programmer is not responding

**Comment by Breidenbach** [comment]
Using Blink - no upload at all.

Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 928 bytes (2%) of program storage space. Maximum is 32,256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2,039 bytes for local variables. Maximum is 2,048 bytes.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/buildd5ae82e677127ac286f51de66781d807.tmp/Blink.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
avrdude: ser_open(): can't open device "/dev/cu.usbmodem1A21": No such file or directory
ioctl("TIOCMGET"): Inappropriate ioctl for device

avrdude done.  Thank you.

Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by cmaglie** [comment]
I've been expecting an error similar to the last ones you sent, instead this time it seems that the wrong port was selected?

> avrdude: ser_open(): can't open device "/dev/cu.usbmodem1A21": No such file or directory

Anyway, from the previous log I have no idea on what's happening on your mac, could you please tell us:

* which board is connected (exact model)
* the version of OSX
* if the same problem is happening with IDE 1.6.10? (no need to post the log again just answer yes or no)
* there may be some software installed on your mac that is interfering with the serial port? (I don't know, bluetooth or modem managers that scans all the serial ports periodically, something like that)

**Comment by Breidenbach** [comment]
No, it appears that my USB connection was not solid.  I plugged it in firmly and was able to get the port connected (as checked in Terminal).  With the latest version I tried to program Blink and got the messages below.  I will try with 1.6.10 later today, I have some commitments to take care of right now.

OS X 10.11.6 (El Capitan)
MacBook Pro (15-inch Early 2008)
6GB memory
2.5 GHz Intel Core 2 Duo

I am not aware of any software polling the USB ports.

Arduino: 1.6.11 (Mac OS X), Board: "Arduino/Genuino Uno"

Sketch uses 928 bytes (2%) of program storage space. Maximum is 32,256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2,039 bytes for local variables. Maximum is 2,048 bytes.
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude -C/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf -v -patmega328p -carduino -P/dev/cu.usbmodem1A21 -b115200 -D -Uflash:w:/var/folders/z_/mg2qts097nsfyc46h0tz76jw0000gn/T/buildd5ae82e677127ac286f51de66781d807.tmp/Blink.ino.hex:i 

avrdude: Version 6.0.1, compiled on Apr 14 2015 at 16:30:25
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/hal/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/cu.usbmodem1A21
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
         AVR Part                      : ATmega328P
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PC2
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 3
         Firmware Version: 4.4
avrdude: stk500_recv(): programmer is not responding
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Breidenbach** [comment]
1.6.10 works with Blink and with ArduiniISP

Hal

**Comment by Breidenbach** [comment]
Success on the Mac!  Thanks for your persistence.  Both Blink and ArduinoISP upload.

**Pull request merged**
