### PR TITLE
Only display touch bar on macOS 10.12 and higher

### PR DESCRIPTION
**Pull request by sandeepmistry**
A potential fix to #8274.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@cmaglie @facchinm, @justb4 has confirmed this is working on Mac OS X 10.11.6, see 
https://github.com/arduino/Arduino/issues/8274#issuecomment-445908696.

Also, it behaves as expected on my macOS 10.14.2 laptop.

**Comment by thojdid** [comment]
Hello ! All the download links are dead ... I need this version for macOS.

**Comment by facchinm** [comment]
The download links are dead because this PR has been merged in master. You can safely download IDE Hourly build (from arduino.cc) and it will work just fine.

**Comment by ErickGiffoni** [comment]
> ✅ Build completed.
> 
> Please test this code using one of the following:
> 
> ⬇️ http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-8281-BUILD-816-linux32.tar.xz
> ⬇️ http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-8281-BUILD-816-linux64.tar.xz
> ⬇️ http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-8281-BUILD-816-windows.zip
> ⬇️ http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-8281-BUILD-816-macosx.zip
> ⬇️ http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-8281-BUILD-816-linuxarm.tar.xz
> 
> ℹ️ The `linuxarm` build is still experimental and may not be always available.

I'm having the same problem on #8274 .
I tried do acmes the link above, referred to Mac OS , but I got 404 not found.

**Comment by per1234** [comment]
>I tried do access the link above, referred to Mac OS , but I got 404 not found.

The test builds are deleted when the pull request is merged, since the code will then be available for testing via the hourly build of the Arduino IDE. However, in this case you don't even need to use the hourly build, since Arduino IDE was released with this change already. So all you need to do to benefit from this change is to update your Arduino IDE to 1.8.9. You can download it here:
https://www.arduino.cc/en/Main/Software

**Pull request merged**
