### PR TITLE
add support for Microduino SD

### PR DESCRIPTION
**Pull request by JasonSheng**

### CODE REVIEW

**Comment by JasonSheng** [comment]
Add enhance for SD pin layout to supprot the microduino board. Just like board that listed in this Sd2PinMap.h, such as Teensy, Sanguino.

**Comment by matthijskooijman** [comment]
The commit looks good by itself, though I cannot verify the actual pinouts.

However, I'm wondering if all this pin mapping code is really needed at all? Nowadays, most variants' pins_arduino.h files [expose constants for special pins](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/standard/pins_arduino.h#L38-L44) (like `MOSI`, `MISO`, etc.). Also, the pin mappings are available through macros (https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Arduino.h#L169-L175). I haven't looked at the code how these things are used, though.

**Comment by JasonSheng** [comment]
Actually we have tested it. And it only can be used if the Macro is true, so it won't impact the Arduino IDE.

**Comment by JasonSheng** [comment]
BTW, the SD library is very special, and can't change your listed file to support new pinout, so have to change the file "Sd2PinMap.h", this is the only method. Hope you can accept this patch.

**Comment by cmaglie** [comment]
> Also, the pin mappings are available through macros (https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Arduino.h#L169-L175). I haven't looked at the code how these things are used, though.

there is this PR that did it already: https://github.com/arduino/Arduino/pull/121

@JasonSheng may I ask you give it a try with the Microduino? (it does need some minor edits to merge cleanly, but you should be able to use the file SD2PinMap.h from here https://github.com/arduino/Arduino/pull/121/files)

**Comment by JasonSheng** [comment]
@cmaglie , I checked the file Sd2PinMap.h, it didn't use PR 121's change. I am not sure the PR #121 has been accepted. Could you please double check it? If use PR #121, our PR no need again.

The PR #121 was submitted in 2012, that directory is /libraries/SD/utility/Sd2PinMap.h, so far the directory has changed to /libraries/SD/src/utility/Sd2PinMap.h.

**Comment by cmaglie** [comment]
> I am not sure the PR #121 has been accepted.

it wasn't, my request is if you can check if it's working for you so we can move it forward :-)

**Comment by JasonSheng** [comment]
@cmaglie , thanks for your suggestion. I tested the PR#121, it can work perfectly with Microduino and no more impact to Arduino board. That is a very good PR. Could you consider to accept this PR #121 in official repor? Thansk in advance.

**Comment by JasonSheng** [comment]
@cmaglie , @matthijskooijman , I tested the PR#121, works well, after this patch, the user can change the pin layout easily. It is a wonderful PR. Could you consider how to move on?

**Comment by JasonSheng** [comment]
@matthijskooijman , @cmaglie , what's your opinion for this new patch, We have verified it, no issue found.

**Comment by matthijskooijman** [comment]
@JasonSheng, I'm for merging #121, but I expect it is now on @cmaglie's stack, waiting for him to find time to test and merge it.

**Comment by cmaglie** [comment]
Hi @JasonSheng,

yes we are working on this one, #121 will get merged very soon!

**Comment by cmaglie** [comment]
#121 has been merged.

**Comment by JasonSheng** [comment]
@cmaglie , @matthijskooijman thanks a lot.. we weill try our best to popularize the Arduino...

**Pull request closed without merging**
