### PR TITLE
Change double quotes to single quotes

### PR DESCRIPTION
**Pull request by roncapat**
Observe that "." is a string literal, and so is treated as the char '.' plus the null char '\0'. Single quotes reduces the necessary memory for this literal to only one char instead. 
A string literal as the one actually present may require the use of the method "write(const char *str)", so there could be also a performance overhead. 
Another reason to change quotes style is for consistency with line 235.

Signed-off-by: Patrick Roncagliolo <ronca.pat@gmail.com>

### CODE REVIEW

**Comment by roncapat** [comment]
My commits now appear after @matthijskooijman's and @NicoHood's approvals because I signed-off them only this evening, and so the original hashes have changed. Sorry for the inconvenient. Feel free to double-check content, no variations were made from original commits.

**Comment by NicoHood** [comment]
@roncapat What do you mean by signed off? They are not GPG signed or at least if they are you miss-configured github.

**Comment by matthijskooijman** [comment]
@NicoHood, he added Signed-off-by headers.
@roncapat, for this repo we are not currently requiring or actively using signed-off-by headers, though they won't hurt of course.

**Comment by facchinm** [comment]
First two patches looks really good, while I'd avoid merging the GSM related patch (maybe opening another PR on https://github.com/arduino-libraries/GSM is more appropriate)

**Comment by roncapat** [comment]
Let me know if I have to squash the first two commits and pop-out the last
one in order to have only the patch(es) you indicated, or something else.

In the next hours I'll then submit the last patch to GSM library repo.



Il lun 9 gen 2017, 10:07 Martino Facchin <notifications@github.com> ha
scritto:

First two patches looks really good, while I'd avoid merging the GSM
related patch (maybe opening another PR on
https://github.com/arduino-libraries/GSM is more appropriate)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arduino/Arduino/pull/5815#issuecomment-271236892>, or mute
the thread

**Comment by facchinm** [comment]
Simply force pushing on the same branch after removing the GSM related patch is ok IMO

**Comment by roncapat** [comment]
Done. Here are only the patches for core library.

**Comment by facchinm** [comment]
Merged, thanks!

**Pull request merged**
