### PR TITLE
Correcting Value Declaration For ACCEL_Y_PIN

### PR DESCRIPTION
**Pull request by SpiderMatt3825U**
The following definition of the accelerometer's Y axis is incorrect based on the preceding comments:

const byte ACCEL_Y_PIN = A11;

The following would be the correct definition based on the preceding comments:

const byte ACCEL_Y_PIN = A7;

### CODE REVIEW

**Comment by facchinm** [comment]
Thank you @SpiderMatt3825U , nice finding. 
However, your fix breaks all existing Esplora projects that use the accelerometer :smile: 

In fact the comment is wrong while the code is right.
Change it and I'll be glad to accept the PR!

**Comment by SpiderMatt3825U** [comment]
This possibility had also crossed my mind (my apologies, I wasn't setup in my current environment at the time to compile this although the forward effect should have been considered on my part). I will get it tweaked and submitted. Thanks @facchinm!

**Comment by facchinm** [comment]
That comment almost all broken, in fact from the schematics (and the code) the right assignment is
```C
// Accelerometer: x-A5, y-A11, z-A6
// External outputs: D3, D11
// Buzzer: D6
// RGB Led: red-D5, green-D10, blue-D9
// Led 13: D13
```
I'll commit the patch squashing yours and fixing the remaining wrong definitions
Thanks!

**Comment by facchinm** [comment]
Fixed with ae8549c
Thank you @SpiderMatt3825U !

**Pull request closed without merging**
