### PR TITLE
Create Automatic Class Generation Feature

### PR DESCRIPTION
**Pull request by jsmith2021Brandeis**
INTRO: If user goes to sketch menu or enters control+space, the current sketch will be parsed and used to automatically generate the header (.h), body (.cpp), keyword (.txt), and example (.ino) files, which are displayed as tabs

MODS: To accomplish this, I added a folder ArduinoClassGenerator in src/cc, and added ClassGeneratorInterface class to src/processing/app

The only existing files I modified where Editor.java to add the generate arduino class menu option and Sketch.java to allow the IDE to open .txt files for the keywords file

See github project this is made from: https://github.com/jsmith2021Brandeis/Arduino-Class-Maker

And see Arduino Developers Discussion: https://groups.google.com/a/arduino.cc/forum/#!topic/developers/BmrloigD_K4

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @jsmith2021Brandeis ,
thanks for the contribution but we are not going to merge this. 

What I can suggest you is to transform it into an external tool that can be loaded on demand (like https://github.com/me-no-dev/EspExceptionDecoder or https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin ).

If you need any hook from the IDE to accomplish this we'll be glad to add it, but opening txt files is surely out of discussion.

**Comment by jsmith2021Brandeis** [comment]
Hello, thank you for replying

Yes, I am interested in developing an external tool, could you point me to a tutorial for how to do this for the Arduino IDE? My current approach is to copy files into the app/src folders directly

**Comment by facchinm** [comment]
You can use https://github.com/arduino/Arduino/tree/master/build/shared/tools as a starting point to define the interface, although the projects I linked before are more complete and also provide a build script.
Once you build the jar, just copy it to `$sketchbook/tools/$toolname/tool` , restart the IDE and you'll get the entry under Tools menu

**Comment by jsmith2021Brandeis** [comment]
Ok,  I researched the provided examples and Arduino Forums, but I have not  been able to create a tool that shows up in the Arduino IDE tools menu 

Here I use the EspExceptionDecoder tool as an example, but my question is really about the Arduino IDE so I am posting here

### 1) Installing EspExceptionDecoder to Arduino IDE
I have gotten an entry under the tools menu to show up by copying EspExceptionDecoder.jar to the tools folder, what I need to do is compile the EspExceptionDecoder.java source into a jar file that is recognized. This would allow me to create my own tool for the Arduino IDE.

### 2) Executing the  ESPExceptionDecoder make.sh file

I tried to compile the EspExceptionDecoder.java source, but these errors result and the jar file is not created
ESP8266 build errors
Note: executing in Windows 10 via Cygwin

### 3) Creating the .jar file manually

I also tried using these commands to create the jar from source, but they create a jar which does not show up in Arduino IDE tools menu

`javac -target 14 -cp "C:\Program Files (x86)\Arduino\lib\pde.jar;C:\Program Files (x86)\Arduino\lib\arduino-core.jar;C:\Program Files (x86)\Arduino\lib\commons-codec-1.7.jar" -d bin src/EspExceptionDecoder.java`

`jar cvf EspExceptionDecoder.jar EspExceptionDecoder$1.class EspExceptionDecoder$1.class EspExceptionDecoder$2.class EspExceptionDecoder$CommitAction.class EspExceptionDecoder$ElfFilter.class`

Note: When I specify -target 1.8 instead of -target 14 above , I get this error
`warning: target release 1.8 conflicts with default source release 14`

### 4) Request for Help

Could you explain how to remove errors when executing make.sh file in section 1?

Can you explain why the jar file from section 2 doesn't create a tool that shows up in Arduino IDE tools menu?
How can I make target release 1.8 without errors?

Finally, can you provide more detailed information on how to create a tool that shows up in Arduino IDE tools menu because I have not been able to achieve this with provided examples and build scripts? Please include exactly the commands required to execute if possible

I appreciate any help you can offer

**Pull request closed without merging**
