### PR TITLE
MacOSX: CMD+SHIFT-LEFT/RIGHT selects the entire line. Fixes #3238

### LINKED ISSUE #3238: CMD+SHIFT+ARROW should select text on Mac OS X
I believe that the keyboard shortcut for selecting text is wrong on Mac OS X after the introduction of RSyntaxTextArea.

Currently the shortcut is FN+SHIFT+ARROW, but in Arduino 1.6.4 and below it was CMD+SHIFT+ARROW.

### PR DESCRIPTION
**Pull request by ffissore**
/cc @Lauszus

### CODE REVIEW

**Comment by Lauszus** [comment]
@ffissore yes that solves it, but I also think it would be a good idea to add support for CMD+SHIFT+UP/DOWN while we are at it.

**Comment by ffissore** [comment]
@Lauszus what do CMD+SHIFT+UP/DOWN do?

**Comment by Lauszus** [comment]
It should select all text above and below the cursor respectively.

**Comment by ffissore** [comment]
It should already work. I'll know a colleague and steal her mac

**Comment by ffissore** [comment]
Fixed. @ArduinoBot will prepare a build

**Comment by Lauszus** [comment]
Haha @ffissore it is no nice to steal ;)

Anyway it is still not working 100% correct.

I have taken a couple of screenshot in order to explain the current behaviour and what is wrong with it.

Cursor was moved to the end of the line and CMD+SHIFT+LEFT was pressed:
screen1

Then I pressed UP while still holding CMD+SHIFT, instead of continuing the selecting it starts from the cursor position instead:
screen2

This is how it should look like:
screen3

Note I got the last screenshot by manually selecting the text.

**Comment by Lauszus** [comment]
Btw is there anyway to just tell it to use the same behaviour as FN+SHIFT+ARROW, as it is working correctly?

**Comment by ffissore** [comment]
Keyboard mappings are defined in https://github.com/arduino/Arduino/blob/master/app/src/processing/app/syntax/SketchTextAreaDefaultInputMap.java and superclasses. I can't spot FN: I can only see shift, alt, cmd, ctrl.
I've merged this PR because, at least, the implemented behaviour is now more similar to the desired one

**Pull request merged**
