### PR TITLE
Support the Atmel STK500 and JTAGICE3 for ISP

### PR DESCRIPTION
**Pull request by matthijskooijman**
This adds support for the STK500 development board.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
I just added one more commit, that allows programming of slower parts (like brand new 328 chips).

**Comment by cmaglie** [comment]
@matthijskooijman 
for JTAGICE3 it seems a bit overkill to have 3 entries just for that, I'd keep only the slow ISP mode that seems the most common for burning a bootloader, what do you think?

**Comment by matthijskooijman** [comment]
Well, one of the reasons I bought a JTAGICE3, is to get faster uploads on my Pinoccio board (uploading and verifying a 128k sketch takes over a minute through the bootloader). ISP at max speed is fast, JTAG is even faster.

So, perhaps we need submenus for programmers? :-)

**Comment by matthijskooijman** [comment]
I just rebased this PR so it applies cleanly again.

**Comment by matthijskooijman** [comment]
Superseded by #5623.

**Pull request closed without merging**
