### PR TITLE
Add watchdog routines for Due.

### PR DESCRIPTION
**Pull request by bobc**
I am not sure the wdt_* routines are in the right file, but this illustrates the functionality. 

Perhaps it would be better to have a new module called "watchdog.c" to contain these routines, the implementation is specific to processor series.

### CODE REVIEW

**Comment by l-mb** [comment]
Except for one stray newline, the patch looks quite good to me. I'd quite appreciate this functionality to be merged; having a µC detect hangs and recover from them would be extremely useful for long-running projects.

Anything one can do to help this along?

**Comment by bobc** [comment]
Aplogies for delay... :)

I have updated with feedback given by Cristian Maglie in https://groups.google.com/a/arduino.cc/d/msg/developers/_oDWeGC9st4/tIcQOW5L9EUJ

**Comment by facchinm** [comment]
Hi @bobc ,
thanks for your work!
I found a flaw in the patchset regarding the configuration of WDT_MR register.
In fact, asserting WDRPROC bit did not issue a reset on my Due board. 
By simply changing the line 
`timeout = WDT_MR_WDRSTEN | WDT_MR_WDRPROC | WDT_MR_WDV(timeout) | WDT_MR_WDD(timeout);` 
to
 `timeout = WDT_MR_WDRSTEN | WDT_MR_WDV(timeout) | WDT_MR_WDD(timeout);` 
it worked perfectly.
Did it work as committed in your setup? If so, can you try the version with that bit cleared and check if it resets as expected?

**Comment by facchinm** [comment]
Merged in #3111

**Pull request closed without merging**
