### PR TITLE
New macosx build

### PR DESCRIPTION
**Pull request by ffissore**
Upgraded appbundler, doubled build.xml targets so that it can package TWO macosx versions.
`platform=oldmacosx` packages the IDE the old way, with automatic installation of java6
`platform=macosx` packages the IDE so that it uses the most recent jre installed

Hopefully fixes [many issues](https://github.com/arduino/Arduino/issues?q=is%3Aopen+is%3Aissue+label%3A%22OS%3A+OSX%22)

@cmaglie

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
If you're having issues with MacOSX, try this version
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2590-BUILD-139-macosx-new.zip

**Comment by Lauszus** [comment]
Just tested this on Mac 10.9.5 and it works fine.

**Comment by wayoda** [comment]
### Please have a look at issue #1493 !
Your changes to file `BaseNoGui.java` tackle the same problem as in issue #1493 

```
static public File getContentFile(String name) {
    File path = new File(System.getProperty("user.dir"));

    if (OSUtils.isMacOS()) {
      path = new File(BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile();
    }

    return new File(path, name);
  }
```
Near the end of the discussion of #1493 there are solutions for for getting rid of the reference to `System.getProperty("user.dir")` on Windows and Linux . 
The unanswered question remained : "Does this work on a Mac too?"
Well obviously it does.  
This version of the above code should work fine on Windows, Linux and Mac
```
static public File getContentFile(String name) {
      path = new File(BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile();
    return new File(path, name);
}
```
There are only 4 calls to `System.getProperty("user.dir")`,
-   2 in `BaseNoGui.java` 
-  2 in `src/processing/app/windows/Platform.java` 

They all can easily be replaced by  `BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().getPath()`.

Eberhard

**Comment by jlefevre2** [comment]
Just downloaded and tried the fix. It works fine now on Macs with the Oracle Java installs. Thanks

**Comment by wayoda** [comment]
## I was wrong in :
### Please have a look at issue #1493 !

My claim:  ~~This version of the above code should work fine on Windows, Linux and Mac~~
```
static public File getContentFile(String name) {
  path = new File(BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile();
  return new File(path, name);
}
```
was wrong. On a Linux (and windows machine) 
```
`new File(BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile();` 
```
points into the `lib`-directory of the distributed app. To make the file point to the correct location (`user.dir`), another `getParentFile()`call needs to be added.
```
`new File(BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile().getParentFile();` 
```
now the file points to the root-dir of the arduino distribution

Sorry 
Eberhard

**Comment by ffissore** [comment]
Thanks everyone for the feedback :)
@wayoda new implementation of `getContentFile` uses `BaseNoGui.class.getProtectionDomain()...` only on mac. See this [code portion](https://github.com/ffissore/Arduino/blob/ide-1.6.0-appbundler-and-java6/arduino-core/src/processing/app/BaseNoGui.java#L166-L174). Does it make sense?

**Comment by wayoda** [comment]
> @wayoda new implementation of getContentFile uses BaseNoGui.class.getProtectionDomain()... 
> only on mac. See this code portion. Does it make sense?

Yes, it does. I just got a bit carried away.... Sorry for the noise

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
If you're having issues with MacOSX, try this version
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2590-BUILD-141-macosx-new.zip

**Comment by ffissore** [comment]
If you're having issues with MacOSX, try this version
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2590-BUILD-141-macosx-new.zip

**Comment by ffissore** [comment]
This new build fixes an issue when the `Arduino.app` folder name had spaces, `Arduino 2.app` for example

**Comment by ffissore** [comment]
If you're having issues with MacOSX, try this version
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2590-BUILD-142-macosxnew.zip

**Comment by PaulStoffregen** [comment]
Should this page be updated with at least a mention about how to build the 2 different versions?

http://code.google.com/p/arduino/wiki/BuildingArduino

**Comment by ffissore** [comment]
Yes, and we need to migrate those pages on github wiki. Opening a new issue

**Pull request merged**
