### PR TITLE
Wire: Support for repeated starts added to sam Wire library

### PR DESCRIPTION
**Pull request by mattwlowe**
[Issue 2428.](https://github.com/arduino/Arduino/issues/2428)

Description:

Adds support for repeated starts to the Wire library on sam. Currently a stop is forced after every write transaction. Some devices are not tolerant of this behavior, such as the MPR121 capacitive touch sensor and MMA8452Q 3-axis accelerometer. 

Interface changes made to the sam Wire library were also implemented in the avr Wire library to ensure they remain congruent. Behavior of both libraries remain unchanged when called using any previous methods. New behavior is only reachable via the new overloaded member functions.

Tests:

Tested on Due and Mega with MPR121. Verified with logic analyzer.

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @mattwlowe , I took a look at your patch and it doesn't seem ready for upstreaming (magic numbers, unclear operations)
What is wrong with @AmLimit solution on #2428 ? Does't it work with MPR121?

**Comment by mattwlowe** [comment]
Hi @facchinm, this patch **is** @AmLimit's solution. That solution adds a new overloaded method which accepts additional parameters. What I've done is also add the equivalent functionality to the avr Wire library so it behaves consistently across architectures.

I did explore other options to improve the clarity of the code. You can look over those with the two recent commits. While cleaner looking those options bring endianess into the equation. My vote is still for the first solution which seems the most elegant to me. Honestly, I'm not sure a 1-byte shift really constitutes a magic number anyway, but you have three options to choose from. 

It would be nice to get **something** merged upstream to address this issue. There are dozens of forum posts and multiple open issues that would likely be addressed with this patch. If you read the comments on those you'll see it's giving people quite a bit of grief. The bug itself is hard to track down because it requires a logic analyzer and knowledge of the I2C protocol (see below). Different devices also handle the improper requests differently and thus there are a wide range of possible failure modes.

broken_due_rs

**Comment by facchinm** [comment]
Hi @mattwlowe , my apologize, I didn't pay much attention at the SAM part because I knew that AVR already had a way to send a repeated start (through `endTransmission(false)` ).

Now, exposing the same API is always a good thing, I was only concerned by the number `3` and the little explanation about what was going on. You are surely an I2C expert but someone else could read the code and being unable to understand what is happening without some proper comment. 

Something like the following could be OK: 
```
// send a repeated start for device which need to access an internal address
// this function is executed by the hardware TWI module on other processors (for example Due's TWI_IADR and TWI_MMR registers)
```
By the way, the first version of the byteshift was better than the following ones, so I'm going to merge your first commit with some comments added. Of course you can modify them later with another PR.

Thank you very much

PS: I'm leaving the screenshot from SAM3X datasheet here for reference
2015-07-03-163408_1280x768_scrot

**Comment by facchinm** [comment]
Manually merged with 39c3f8b

**Pull request closed without merging**
