### PR TITLE
Removed explicit check for true/false

### PR DESCRIPTION
**Pull request by arnavb**
The title says it all.

### CODE REVIEW

**Comment by arnavb** [comment]
Ok, should I make the changes on those files in this PR?

**Comment by matthijskooijman** [comment]
The other cores live in different repositories, so they'd need different PRs.

@facchinm, @cmaglie, what's the plan for these shared files? I remember some plans to extract them into a shared space, but I'm not sure how far along those plans are? Regardless, what's the best course to take here? Preparing separate PRs, or just copying over the entire Stream.cpp file at some later point?

**Comment by arnavb** [comment]
@matthijskooijman You said this was safe to merge a few months ago. Any chance of this actually happening? (Sorry to pester you)

**Comment by matthijskooijman** [comment]
@arnavb, I'm not in a position to merge things, I usually only review stuff. You'll have to pester @cmaglie and @facchinm instead :-p

**Comment by arnavb** [comment]
Well, since you've pinged them, that's good.

**Comment by facchinm** [comment]
Hi @arnavb , sure, we are in the middle of a transition to https://github.com/arduino/ArduinoCore-avr so I'd prefer not to merge the PR here but to merge it there. Furthermore, as you can see from the "Print and Stream class" tag, it is not an hardware related change so it's going to be merged as part of Chainsaw project. Sorry for the confusion about all these repos but we are trying to provide on a more modern way to contribute to the project.

**Comment by arnavb** [comment]
@facchinm Makes sense!  Thanks for the info!

**Pull request closed without merging**
