### PR TITLE
implement joystick-USB-api from diff

### PR DESCRIPTION
**Pull request by nieknooijens**
implementend joystick support for arduino devices.

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by NicoHood** [comment]
Similar as this one:
https://github.com/arduino/Arduino/pull/2843

**Comment by facchinm** [comment]
Closed with #1803

**Comment by NicoHood** [comment]
You may use this now:
https://github.com/NicoHood/HID/tree/dev_2_4

**Pull request closed without merging**
