### PR TITLE
Fix long DHCP lease times 

### PR DESCRIPTION
**Pull request by chaveiro**
Fix for lease times > 7FFFFFFF seconds.
Forever lease time is unsigned long with value FFFFFFFF.
If lease time > 7FFFFFFF, calling Ethernet.maintain() would force a renew every time. That is wrong, overloads dhcp server and generates unnecessary network traffic.
Issue was described here: https://code.google.com/p/arduino/issues/detail?id=985

### CODE REVIEW

**Comment by chaveiro** [comment]
This is related to https://github.com/arduino/Arduino/issues/985 and https://github.com/arduino/Arduino/issues/2571

**Comment by Elijahg** [comment]
This does *not* fix #2571 entirely. It needs a fix in Dhcp.cpp too.

**Comment by chaveiro** [comment]
Please be specific what you mean entirely. My fix is for DHCP lease time.

**Comment by cmaglie** [comment]
This has been included in #3287 please follow up there.

**Pull request closed without merging**
