### PR TITLE
Added the last three zero-error (for a 16 MHz system clock) Baud rate…

### PR DESCRIPTION
**Pull request by dsstutts**
…s (500,000.0, 1,000,000.0, and 2,000,000.0) to the list of available serial speeds in SerialMonitor.java.  All performed flawlessly in my tests.

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @dsstutts , I think you had a problem with file permissions (all became executable) and got committed. Would you mind fixing it and force pushing over your previous commit?

**Comment by dsstutts** [comment]
Martino,

Sorry about that!  When I first tried to build the app after my changes, the build failed because the GET of liblistSerials-1.2.0.zip failed (the .zip was incomplete or corrupted), so thinking that there was a issue with my git clone, I built from a zipped master I downloaded with no changes.  This one built fine, as an uncorrupted and complete liblistSerials-1.2.0.zip was downloaded.  I then simply copied the whole unzipped directory into my repo — in retrospect, obviously a dumb thing to do — failing to realize that gunzip creates a 0777 copy of everything in the zip!  DOH!

My solution was to simply re-clone the Arduino Master, make the one change, and force-push to my remote.

I don’t know why my first attempts to build from my git clone resulted in a filed GET during the build process, but the downloaded zipped version ran to completion; do you have any idea why this might happen?

Thanks for catching that, and best regards,

Dan
--
Dr. Daniel S. Stutts
Associate Professor of Mechanical Engineering
Missouri University of Science and Technology
282 Toomey Hall
400 West 13th St.
Rolla, MO 65409-0050
(573) 341-4084<tel:%28573%29%20341-4084>
Fax: (573) 341-4607<tel:%28573%29%20341-4607>
http://www.mst.edu/~stutts

**Comment by dsstutts** [comment]
Martino,

I just tried to build from my newly-cloned Arduino master, and found that liblistSerials is still being corrupted during the GET process.  I’ve attached the offending file FYI.  It appears to be incomplete since the uncorrupted version is 394 KB.  The build completed successfully when I replaced it with the one complete liblistSerials-1.2.0.zip that downloaded with I ran the build from the zipped master that I downloaded.

I’m working on a MacBook Pro running El Capitan Vers. 10.11.6 (15G1108) with java Vers. 1.8.0_92, Java SE RE build 1.8.0_92-b14.

Any suggestions as to what might be going on here?

Again, best regards,

Dan
--
Dr. Daniel S. Stutts
Associate Professor of Mechanical Engineering
Missouri University of Science and Technology
282 Toomey Hall
400 West 13th St.
Rolla, MO 65409-0050
(573) 341-4084<tel:%28573%29%20341-4084>
Fax: (573) 341-4607<tel:%28573%29%20341-4607>
http://www.mst.edu/~stutts

**Comment by facchinm** [comment]
Merged as a095d2a3c8db3d6634abe612c9949ccca6545371, thanks!

**Pull request closed without merging**
