### PR TITLE
Improved Blink example comment wording

### PR DESCRIPTION
**Pull request by parzivail**

### CODE REVIEW

**Comment by per1234** [comment]
I'm not trying to single you out on this. Clearly you're just following the long established precedent but I think Arduino needs to reconsider the practice of putting the changelog at the top of the examples. I think it's best to avoid any unnecessary lines in the examples, keep them as short and simple as possible. These changelogs are going to get longer as time goes by and it's just not beginner friendly to have to scroll through pages of meaningless text to get to the actual code. If the developers really think a changelog is necessary(I don't because it's already on GitHub) then add it as a separate file. It's nice to give people credit but the release notes and the GitHub contributors tab should be sufficient.

**Comment by parzivail** [comment]
Simple enough. Left them for reference in the commit message.

**Comment by connornishijima** [comment]
+1 - I agree that this wording makes more sense to me, and that changelogs should stay out of source in this case. Instead I think the code could link to the commit history of the sketch or something similar.

**Comment by matthijskooijman** [comment]
@cmaglie, @facchinm, see comments above. How about removing the changelogs from all examples? Or even from all source files? Seems they're no longer actually useful. I would suggest keeping copyright notices, and in the future still add copyright notices when contributors add significant portions of code to a file.

**Comment by cmaglie** [comment]
If it was for me I'd just leave the copyright notice and the names of the authors, without the changelog, but I have to clear this internally before proceeding, so for now I'll merge only the commit with the wording improvement.

BTW, removing the changelog from all the examples is a boring and time consuming task. that gives (very) little advantage. Maybe a better approach is to not use changelog on new examples and slowly remove the changelog from the existing examples when there is a chance.

**Comment by per1234** [comment]
I volunteer to remove the changelog from all examples and/or source files if that's approved. Just give me the go ahead and I'll submit a pull request. I would also need to know whether to do everything in one PR here or do each of the libraries in separate PRs submitted to the arduino-libraries repos.

**Pull request closed without merging**
