### PR TITLE
  Add EthernetClient getSocketNumber() function

### PR DESCRIPTION
**Pull request by bigjohnson**
This is the correction of pull request #2844

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by Chris--A** [comment]
Is there something holding back this PR?

It seems a fairly harmless, but useful addition.

**Comment by facchinm** [comment]
Indeed the PR is clearly both useful and harmless. I'll merge and add the keyword for highlighting.
Thanks!

**Comment by facchinm** [comment]
Merged as  c5f0815f2

**Comment by PaulStoffregen** [comment]
I'm wondering why this is useful?

**Comment by Chris--A** [comment]
Multiple connections being managed by a single end point needs some method of determining where the data came from. This is fine if you can build your code around EthernetClient, however some unrelated code may only accept/use blocks of data with ID's (socket in this case).

**Pull request closed without merging**
