### PR TITLE
Add serial input text field to plotter

### PR DESCRIPTION
**Pull request by cactorium**
This adds an input text field to the Serial Plotter so that input can be transmitted to the Arduino while receiving plottable data. Most of it was just copied from `AbstractTextMonitor` and `SerialMonitor` into `SerialPlotter`

### CODE REVIEW

**Comment by ElectricRCAircraftGuy** [comment]
@cactorium , this looks useful. Are you going to fix the issue the automatic check found?

**Comment by cactorium** [comment]
Oh, I didn't see that, give me a couple minutes

**Comment by cactorium** [comment]
@ElectricRCAircraftGuy Just checking in, I think it's passing the check now

**Comment by ElectricRCAircraftGuy** [comment]
Awesome. I'm just a third party observer though so unfortunately I can't do anything to help it land. I'm just watching this is all.

**Pull request merged**
