### PR TITLE
Bridge: fix transfers which ignored host response

### PR DESCRIPTION
**Pull request by facchinm**
Bridge.put() was broken by #2781 because it used transfer() 2-parameters overloaded version, which imply that rxlen == 0.
But the Linux Bridge responded, so the check (i >= rxlen) was true and the function timed out after retrying 50 times.

Every bridge command (python side) has been checked and now SHOULD strictly follow this rule and never ignore silently the received data

### CODE REVIEW

**Comment by ffissore** [comment]
Can you also increase version in library.properties?

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by cmaglie** [comment]
Please check also the `Bridge::get()` command: the host sends back an "unbounded" response, so it may exceed the reserved buffer.

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
Let's make another build since we pushed lots of fixes in the last two days

**Pull request merged**
