### PR TITLE
Add file downloader cache to make faster the library/boards manager

### PR DESCRIPTION
**Pull request by mattiabertorello**
- Add the cache for the library and boards files 
- Fix the delete of the files when something fail during the signature check
- Add this configuration: `http.connection_timeout_ms` with 5000 as a default value, `cache.enable` with true as a default value 
- Add logging on local file Arduino15/logs/application.log (rotation policy: compress if the log is bigger than 50MB, delete when there are more than 20 compressed log files. See app/src/log4j2.xml)

Fixed issues: https://github.com/arduino/Arduino/issues/8936, https://github.com/arduino/Arduino/issues/6333, https://github.com/arduino/Arduino/issues/7690#issuecomment-397550877
Mitigated: https://github.com/arduino/Arduino/issues/8988

The cache will consider the "Cache-Control" and the ETag headers. 
So if the server delivers a file, setting a `Cache-Control="private, max-age=14400"` http header, the file will be cached for 4 hours without make any http request. When the cached file expires the download will make a HEAD request to check for ETag header changes, before making an actual download request.
Trying to emulate the browser behavior: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

The metadata of the cached files will be store in the Arduino15/cache/cache.json
example:
```
{
  "files" : [ {
    "eTag" : "a778ceeb5945afa31275495b8ccd5434",
    "remoteURL" : "https://downloads.arduino.cc/packages/package_index.json.sig",
    "localPath" : "/Users/mattiabertorello/Library/Arduino15/cache/downloads.arduino.cc/packages/package_index.json.sig",
    "md5" : "MD5:a778ceeb5945afa31275495b8ccd5434",
    "createdAt" : "2019-07-03T15:46:58.877",
    "cacheControl" : {
      "maxAge" : 14400,
      "public" : false,
      "private" : true,
      "mustRevalidate" : false,
      "noCache" : false,
      "noStore" : false,
      "noTransform" : false,
      "proxyRevalidate" : false,
      "smaxAge" : -1
    },
    "expires" : "2019-07-03T19:46:58.877"
  }]
}
```

### CODE REVIEW

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by per1234** [comment]
I did a test using a throwaway Boards Manager JSON file I published here:
https://gist.github.com/per1234/ed63fa1f88e7cff876620053378e895b/raw/80bc2b996db7fd878dfbe86dd2024490f57fecc6/package_foo_index.json
This file intentionally has a bad package file URL for the 1.0.4 release so installation is expected to fail. With Arduino IDE 1.8.10 Hourly Build 2019/05/21 09:33 I get this clear error message:
```
 Error downloading https://MCUdude.github.io/MicroCoreFoo/MicroCore-1.0.4.tar.bz2
java.lang.RuntimeException: java.lang.Exception: Error downloading https://MCUdude.github.io/MicroCoreFoo/MicroCore-1.0.4.tar.bz2
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://MCUdude.github.io/MicroCoreFoo/MicroCore-1.0.4.tar.bz2
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:139)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:73)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:55)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:101)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 404
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:205)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:132)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:137)
	... 5 more
```
But with build 871 I get this:
```
 Error downloading https://MCUdude.github.io/MicroCoreFoo/MicroCore-1.0.4.tar.bz2
java.lang.RuntimeException: java.lang.Exception: Error downloading https://MCUdude.github.io/MicroCoreFoo/MicroCore-1.0.4.tar.bz2
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading https://MCUdude.github.io/MicroCoreFoo/MicroCore-1.0.4.tar.bz2
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:142)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:76)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:58)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:103)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Caused by: java.nio.file.FileSystemException: C:\Users\per\AppData\Local\Arduino15\staging\packages\MicroCore-1.0.4.tar.bz2: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:189)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:129)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:140)
	... 5 more
```
Note the error message now says "The process cannot access the file because it is being used by another process." instead of "Received invalid http status code from server: 404".

C:\Users\per\AppData\Local\Arduino15\staging\packages\MicroCore-1.0.4.tar.bz2 didn't exist on my computer before the installation attempt. It is a 0 byte file that was created during the installation. The error message "The process cannot access the file because it is being used by another process." makes me think of a conflict with an antivirus software's on-access file scanner, but this is not the case because I tried with the antivirus disabled and it still happens. I feel like this error message could be very misleading to someone trying to troubleshoot this problem because it acts as a distraction from the real problem that the file couldn't be downloaded, and also blocks the helpful HTTP response code from being shown.

I also tried with build 871 running in portable mode, with the same error message.

On my Linux machine, I get the "Received invalid http status code from server: 404" error from build 871.

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by mattiabertorello** [comment]
I should fix the problem but I can't test on windows, could you test it ? @per1234 
Thanks

**Comment by per1234** [comment]
@mattiabertorello looks good. Thanks!

**Comment by feikname** [comment]
Does this solve #6333?

**Comment by facchinm** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@feikname yes, this PR should address also your issue.
It would be great if you can help us in testing the preview binary available in the comment above (this one: https://github.com/arduino/Arduino/pull/9023#issuecomment-508121494) and attach in a comment here the logs (available in the `Arduino15/logs/application.log` folder as described in the PR summary) if you experience any sort of issues. 
Thanks a lot!

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by per1234** [comment]
>Fix the delete of the files when something fail during the signature check

I'm still experiencing the file being deleted when the signature verification check fails using build 880.

Since I've never had a problem with signature verification of https://downloads.arduino.cc/packages/package_index.json, I had to contrive a system to simulate this error by creating a throwaway Boards Manager JSON file and a dummy .json.sig file that will cause a failed signature verification.

1. File > Preferences
2. Add the following URL to "Additional Boards Manager URLs": https://gist.githubusercontent.com/per1234/ed63fa1f88e7cff876620053378e895b/raw/ca1dfe102436d6335abb06fdf828c1f8e6a0222a/package_foo_index.json
3. Click the "OK" button.
4. Tools > Board > Boards Manager
5. Install the "MicroCore" package provided by the above JSON file.
6. Click the "Close" button. You can now see the MicroCore's ATtiny13 board under the **Tools > Board** menu.
7. Close the Arduino IDE
8. Note that the file package_foo_index.json is present in the Arduino IDE's data folder.
9. Add the following line to preferences.txt to cause the signature verification to occur on that domain: `http.signature_verify_domains=gist.githubusercontent.com`
10. Start the Arduino IDE (build 880).
11. Tools > Board > Boards Manager

The error message:
```
https://gist.githubusercontent.com/per1234/ed63fa1f88e7cff876620053378e895b/raw/ca1dfe102436d6335abb06fdf828c1f8e6a0222a/package_foo_index.json.sig file signature verification failed. File ignored.
```
is shown in the console, the ATtiny13 board is lost from the **Tools > Board** menu, and the file package_foo_index.json is deleted from the Arduino IDE's data folder.

**Comment by per1234** [comment]
I've attached the application.log file produced by following the instructions in my previous reply, as requested:
[application.log](https://github.com/arduino/Arduino/files/3362831/application.log)

---
One correction to my instructions above: I forgot to mention that you need to install MicroCore 1.0.3 in step 5 because I purposefully broke the package download URL for 1.0.4 to test the issue I reported last week.

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by red-scorp** [comment]
[application.log](https://github.com/arduino/Arduino/files/3363565/application.log)

You know what's funny, I put this setup to 'portable' mode but it is still using my user directory C:\Users\AG\AppData\Local\Arduino15\cache\downloads.arduino.cc\packages\package_index.json 
Have fun!

**Comment by per1234** [comment]
I tested build 881's behavior on signature verification failure and download failure and it's working perfectly now. Great work!

---
There is one thing I noticed, though it's probably a non-issue in real life:

As far as I understand, before this PR, the way the signature verification system worked was the IDE would look for a file of the same name as the .json file, but with the .json.sig extension. If this file was found, the signature of the .json file would be verified. If the file was not found, no signature verification was attempted.

After this PR, by default the signature verification system is only attempted on the downloads.arduino.cc domain, even if a .json.sig file is present on other domains. You can specify a list of domains to do signature verification on using the `http.signature_verify_domains` property. However, the behavior is now different. Instead of only doing signature verification if the .json.sig file is present, the download now fails for any .json file under the specified domains that doesn't have a .json.sig file.

Many 3rd party Boards Manager URLs are under the raw.githubusercontent.com or github.com domains. So this new behavior would make it very inconvenient for someone to enable signature verification for one of those Boards Manager URLs if they have other Boards Manager URLs under the same domain which don't have a .json.sig file.

The truth is that it's likely no 3rd party hardware cores are using the signature verification system, though the lack of documentation of this feature may be partly to blame. So the changed behavior may not actually be a problem in real life. However, I'm having trouble understanding what the benefit is of this signature verification whitelisting system.

The signature verification feature seems like something that could potentially be considered useful by some 3rd party core authors if they were made aware of it and how to use it via proper documentation (probably [here](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.6.x-package_index.json-format-specification)). Even if the previous behavior of only doing a signature verification when the .json.sig file is found was restored for the whitelisted domains, the requirement for users of 3rd party hardware cores to specify a custom whitelist to make the signature verification feature work on those cores makes it much less useful.

**Comment by rsora** [comment]
@ArduinoBot build this please

**Comment by Michael-List** [comment]
With the build 881 & 882 the problem is fixed for me (Germany)

**Comment by rsora** [comment]
@per1234 consider the signature whitelisting a foundation for implementing in near future a 3rd party indexes security mechanism without breaking retro-compatibility.

Currently the signature check mechanism uses a public and private keys and consists in signing the Arduino's package_index.json server side with our private key, and checking the signature in the IDE using the Arduino's public key bundled in the IDE.

We are investigating in ways to make more secure also 3rd party cores indexes, maybe starting using our own key end ending up having some sort of CA mechanism similar to the one used by web browsers. But this is not so easy to implement so we implemented only the first bits of the feature. 

I hope that this clarifies your doubts, otherwise, feel free to ask for details :)

**Comment by red-scorp** [comment]
Germany. Same error https://downloads.arduino.cc/packages/package_index.json.sig file signature verification failed. File ignored.
I put 882 in portable mode and this is my log: 
[application.log](https://github.com/arduino/Arduino/files/3385317/application.log)

**Comment by rsora** [comment]
@ArduinoBot build this please

**Pull request merged**
