### PR TITLE
Fix for #2402

### PR DESCRIPTION
**Pull request by swordmaster2k**
Fix for #2402 

To test simply create a series of tabs with content you want to replace, select a tab to the right of the first tab. Go to Edit->Find, enter text to replace and what to replace it with, select Search all Sketch Tabs, then press Replace All.

Result: search will start from the first tab and precede along the list.

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by per1234** [comment]
FWIW I've been using this build on a daily basis for a couple weeks now with no problems. Thank you swordmaster2k for this important fix! I hope it will be merged soon. Per

**Comment by per1234** [comment]
@ffissore is there anything you can do to get this merged? This bug was introduced to the IDE 2014-10-01,  I reported it 2014-11-02, swordmaster2k fixed the bug 2015-02-16. Since then there have been two IDE versions released and still the bug is there. I am inconvenienced by this issue at least once a week(even though I know about it I still forget). I'm sure I'm not the only one. This is a very serious bug with a very simple fix. There is no reason it should still be in the IDE.

**Comment by matthijskooijman** [comment]
I can't speak for Federico, but I can review this PR. The code looks ok to me, though I haven't looked in detail.

The commit messages and structure can use a bit of improvement, though. Ideally, there would be just one commit with the fix, instead of having the fix spread out over two commits, with a merge in between. It is accepted and encouraged to amend, rebase and/or force-push a branch in your own repository, when that branch forms the basis of a pullrequest.

The resulting single commit should furthermore start with a short summary of what was changed. "Fix for #sombugnumber" isn't really helpful here - commit messages should be self contained. "Start search and replace all from first tab" would be better first line. The subsequent lines could detail the problem and solution, and include a "Closes #2402" line to reference the bugreport.

Could update your PR with the above suggestions?

**Comment by per1234** [comment]
@swordmaster2k do you have any plans to update your PR in accordance with matthijskooijman's recommendations? I'm willing to give it a try, but don't want to hijack your work.

**Pull request merged**
