### PR TITLE
IDE: prevent multiple 'bad name' notifications.

### PR DESCRIPTION
**Pull request by Chris--A**
This patch will prevent the IDE from informing the user about a bad sketch folder name multiple times. Now the user is informed once at start up only, or once when it is detected during a re-scan of the folders.

Here is a run down of what I have noticed. Being bugged twice by V1.5.7 was fine, but now its a minimum of eight times. This only involves one folder with an invalid name.

#### Version 1.5.7
- *twice on start up.*
- *once on board change.*
- *no board manager to compare*

#### Version 1.6.3
- *eight times on start up.*
- *four on board change.*
- *eight on opening of board manager.*
- *four on closing board manager.*

#### Version 1.6.4
- *eight times on start up*
- *four on board change*
- *six on board manager open*
- *eight on board manager close.*

In 1.6.4 simply starting the IDE, opening/closing the board manager and changing board types generates 26 notification boxes for me to click.

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by Chris--A** [comment]
Downloading windows version now, will test it soon.

**Comment by Chris--A** [comment]
Threw a *__NullPointerException__* on usage of the static variable.

Being very new to java I overlooked the type semantics. List is apparently a reference object, so I have modified it accordingly (create a *new* object to reference).

**Comment by Chris--A** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
```
compile:
    [mkdir] Created dir: /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/bin
    [javac] Compiling 121 source files to /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/src/cc/arduino/contributions/libraries/LibrariesIndexer.java:61: error: List is abstract; cannot be instantiated
    [javac]   private static final List<String> badLibNotified = new List<String>();
    [javac]                                                      ^
    [javac] Note: /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/src/processing/app/preproc/PdePreprocessor.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning
```

**Comment by Chris--A** [comment]
Thank you,
On searching the error, I found this article which explained it for me nicely. http://stackoverflow.com/a/6810696/4057102

If I plan to do more IDE mods, I'll get a working compiler solution set up to avoid these errors.

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
```
compile:
    [mkdir] Created dir: /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/bin
    [javac] Compiling 121 source files to /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/src/cc/arduino/contributions/libraries/LibrariesIndexer.java:61: error: cannot find symbol
    [javac]   private static final List<String> badLibNotified = new ArrayList<String>();
    [javac]                                                          ^
    [javac]   symbol:   class ArrayList
    [javac]   location: class LibrariesIndexer
    [javac] Note: /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/arduino-core/src/processing/app/preproc/PdePreprocessor.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning
```

I guess you really need to set up a dev env :)

**Comment by Chris--A** [comment]
Yeah, I'm setting one up now.
Cheers.

**Comment by Chris--A** [comment]
Had success, it works as I expected.
I finally managed to work out how to squash my commits.

I got an error with the `ant run` process, however copying in the java folder from my 1.6.4 version allowed it to run.

> windows-run:
spawn does not allow attributes related to input, output, error, result
spawn also does not allow timeout
finally, spawn is not compatible with a nested I/O <redirector>
>
BUILD FAILED
F:\Arduino\build\build.xml:71: The following error occurred while executing this line:
F:\Arduino\build\build.xml:869: You have used an attribute or nested element which is not compatible with spawn

**Comment by Chris--A** [comment]
With the fix I proposed to build.xml in #3167 this compiles and runs perfectly.

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by Chris--A** [comment]
Arduino bot's having a long weekend.

**Comment by ffissore** [comment]
Yup, a maintenance activity left it disabled. Just re-enabled it

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
Rebased on master and pushed. See b2f8b9b6c16d9ab3eeca25ba8082128a08b47ef7. Thanks!

**Pull request closed without merging**
