### PR TITLE
Refactor Print.cpp for consistency

### PR DESCRIPTION
**Pull request by roncapat**
- Uniformed parameters (str, num) across "print" and corresponding "println". 
- Reorder methods to better separate non-ln and ln versions.

Signed-off-by: Patrick Roncagliolo <ronca.pat@gmail.com>

### CODE REVIEW

**Comment by matthijskooijman** [comment]
This looks like a sane cleanup to me.

This is related to (mostly in the sense that it touches the same code and will probably conflict) to #5829.

**Comment by roncapat** [comment]
Ok, I'll wait for the #5829 to merge and then fix the patch in this PR

**Comment by cousteaulecommandant** [comment]
#5829 actually removes println from Print.cpp (except for println(void)), so that weird order issue is already handled by that.  The random arg names still persist though; it is true that they're a bit confusing.

**Comment by roncapat** [comment]
I had a look to your PR (#5829), and I think it's a great cleanup. When it's merged, maybe I'll check for arg names refactor. I subscribed to your PR so I'll know when to rebase and start from updated sources.

**Comment by roncapat** [comment]
Closing for obsolescence

**Pull request closed without merging**
