### PR TITLE
Refactor port selection after 1200bps touch upload

### PR DESCRIPTION
**Pull request by facchinm**
New behaviour:
if upload failed or we are uploading through a "Programming" port (that does not disappear), leave the user selected port selected.
if upload succeded and we are using 1200bps touch, wait for the first port that reappears, and if nothing reappears after the timeout select the bootloader port.

Fixes https://github.com/arduino/Arduino/issues/3495

### CODE REVIEW

**Comment by matthijskooijman** [comment]
I haven't looked at the code in detail, but can't we match the port based on the USB identifier (I mean the connection path / USB port, not the vidpid).

**Comment by facchinm** [comment]
Matching on the usb identifier would be THE BEST; I tried that approach once with libusb hotplug but it didn't really work :slightly_smiling_face: Anyway, any help on this would be greatly appreciated.

**Comment by PilotinControl25** [comment]
Ok so this build works under windows Vista by pressing the reset button and it uploads....any way of not doing that each time?

**Comment by facchinm** [comment]
@PilotinControl25 which board are you targeting?

**Comment by cmaglie** [comment]
The fix looks good, it should cover new cases without touching the existing one. I'm merging this one so it may get broader testing on the hourly build.

**Pull request merged**
