### PR TITLE
fix delay/yield issues on avr

### PR DESCRIPTION
**Pull request by vbextreme**
fix delay/yield issues #4320 on avr

### CODE REVIEW

**Comment by NicoHood** [comment]
I think you could leave out the (uint32_t) since it is 32 bit anyways?

**Comment by vbextreme** [comment]
oversight.
thanks.

**Comment by matthijskooijman** [comment]
Code looks good to me. Some remarks about the commits themselves:
 - The commit changes the indentation from (I think) 8 spaces or one tab to 2 spaces. Please do not do this, since this makes the commit harder to review later, and makes the indentation inconsistent with the surrounding code.
 - Please merge all commits into one (You can use git rebase for that, see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History )
 - Please add a more detailed commit message, with a first short line that summarizes the change (e.g. "Fix delay() when yield() takes more than 1ms", an empty line and a more detailed description).

**Comment by Testato** [comment]
+1
thanks VBextreme for this PR

**Comment by vbextreme** [comment]
@matthijskooijman , I could not merge the commits. 
I have try to rebase but not working, you can help me?

**Comment by matthijskooijman** [comment]
@vbextreme, I see you deleted your comment asking for help with the rebasing. I'm happy to help, but you'll have to tell me what you tried and where you got stuck. Alternatively, feel free to drop by on the #arduino IRC channel on [Freenode](https://webchat.freenode.net/), I'm "blathijs" there. I should be online during office hours most of the time (GMT+1).

**Pull request closed without merging**
