### PR TITLE
Library debug

### PR DESCRIPTION
**Pull request by Lauszus**
Print library name when installing via library manager and don't throw exception if library is already installed.

### CODE REVIEW

**Comment by Lauszus** [comment]
This especially makes sense when multiple libraries are installed at once: https://github.com/arduino/Arduino/pull/2947.

**Comment by ffissore** [comment]
Thanks! I'll change error messages a bit so that they play more nicely with i18n

**Comment by Lauszus** [comment]
Okay thanks. I was wondering about that as well, but just submitted it anyway ;)

**Comment by ffissore** [comment]
Thank you :) This is the commit f0cc644d8f60c65a95f6e5bc0e74c68feb1a2fd7 . It plays nicer because only string `"Library is already installed: \"{0}\""` is extracted and translated. This also allows translations to move `{0}` around, to fit a particular grammar

**Pull request merged**
