### PR TITLE
Keep Serial Monitor open during upload

### PR DESCRIPTION
**Pull request by holgerlembke**
Keep Serial Monitor open during upload and don't break existing functions. I became aware that there is another solution after I did my implementation. So perhaps it is obsolete...

=====
First try to work with Github, I need a nanny... :-)

### CODE REVIEW

**Comment by matthijskooijman** [comment]
There have been a few versions of solutions for this problem. The "accepted" solution so far is to disable the serial monitor during uploads, without closing the window. This is implemented by #2742. If you want to help out, you could perhaps test that code and report your findings?

Still, thanks for your contribution! Hopefully more to come?

If you think your PR adds something to #2742, please tell us what. Otherwise, it is probably better to close this PR?

**Comment by holgerlembke** [comment]
As far as I see, there are some notes that #2742 does not work on all platforms.

Perhaps this solution is more compatible...

**Comment by PaulStoffregen** [comment]
@ArduinoBot build this please

**Comment by holgerlembke** [comment]
Hmm. Sorry for any confusion, but apparently I managed to add another change to this pull request. I intended to create two different pulls, on for each commit, but I failed. And I fear to create more chaos if I remove the second commit now.

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
It looks the bot is sleeping

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
Ok, it doesn't compile
```
compile:
    [mkdir] Created dir: /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/app/bin
    [javac] Compiling 65 source files to /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/app/bin
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/jenkins/jenkins/jobs/arduino-pull-request-builder/workspace/app/src/processing/app/NetworkMonitor.java:25: error: NetworkMonitor is not abstract and does not override abstract method closeSerial() in AbstractMonitor
    [javac] public class NetworkMonitor extends AbstractMonitor implements MessageConsumer {
    [javac]        ^
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning
```

**Comment by holgerlembke** [comment]
Mine here does.

**Comment by holgerlembke** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@holgerlembke I've tried it locally and fails the same way. Your commit https://github.com/holgerlembke/Arduino/commit/16adf827eee5600599b3efc36d4a9bd5811822a3 is about one blank line added

**Comment by holgerlembke** [comment]
@ArduinoBot build this please

**Comment by holgerlembke** [comment]
@ArduinoBot build this please.

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Pull request closed without merging**
