### PR TITLE
Allow per-platform keywords.txt

### PR DESCRIPTION
**Pull request by PaulStoffregen**
This patch allows platforms to define an keywords.txt file, to add their unique keywords.  When a board change also changes platforms, the keywords are reloaded and all editor windows updates with the new keywords.

### CODE REVIEW

**Comment by NicoHood** [comment]
Would this also fix https://github.com/arduino/Arduino/issues/2996 ?

**Comment by PaulStoffregen** [comment]
Yes, I believe it should partially fix #2996.

The keywords are only re-read when changing architecture folders.  If you have a AVR board which uses hardware/arduino/avr for its boards.txt and platform.txt and you switch to a different board, keywords will **not** be re-read if the new board also uses hardware/arduino/avr.  But if you switch to a board that uses hardware/HoodLoader2/avr as its boards.txt and platform.txt, then keywords will be re-read.

Any chance you could give the arduinobot build a quick try?  Would be nice if someone (other than me) could at least confirm it works in at least 1 quick test...

**Comment by NicoHood** [comment]
The specific issue I linked is fixed with this.

**Comment by PaulStoffregen** [comment]
Good :)

Is the assumption correct that keywords only need to be re-read when a board change switches to a new architecture folder?  Are there any cases where this would be needed changing between boards that share the same architecture folder?

**Comment by NicoHood** [comment]
I think the behavior is correct like this. I havent looked at the patch itself but from the logic you described it is correct, no need for a further change.

**Comment by lmihalkovic** [comment]
[LMNTS]

**Pull request merged**
