### PR TITLE
New proxy tab in preferences

### PR DESCRIPTION
**Pull request by ffissore**
Someone is having issues when using libs/boards manager behind corporate proxies (corps or universities)

Previous attempts to rely on system proxy settings were not successful, sometimes because of how such corporate PCs are configured. (see #3604)

We must give up and provide a complete proxy configuration settings panel

/cc @McNeight

### CODE REVIEW

**Comment by McNeight** [comment]
Just tested arduino-PR-3637-BUILD-377-windows from behind the firewall. Manual proxy settings work well, but the auto-detect setting has the following errors:
```
Error downloading http://downloads.arduino.cc/packages/package_index.json
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$23(ContributionManagerUI.java:149)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$$Lambda$81/32267106.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/packages/package_index.json
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:113)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:318)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:294)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:276)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$23(ContributionManagerUI.java:145)
	... 2 more
Caused by: javax.script.ScriptException: ReferenceError: "myIpAddress" is not defined in <eval> at line number 106
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:387)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:187)
	at cc.arduino.net.CustomProxySelector.callFindProxyForURL(CustomProxySelector.java:83)
	at cc.arduino.net.CustomProxySelector.pacProxy(CustomProxySelector.java:60)
	at cc.arduino.net.CustomProxySelector.getProxyFor(CustomProxySelector.java:35)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:125)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	... 6 more
Caused by: <eval>:106 ReferenceError: "myIpAddress" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:914)
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$3549AA$\^eval\_.FindProxyForURL(<eval>:106)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:192)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:381)
	... 12 more
```

This was with the non-debug executable. Let me know if running the debug executable provides you with more useful information, and I'll run that instead.

-Neil

**Comment by ffissore** [comment]
Argh, that's because I've implemented support only to main `FindProxyForURL` function. I'll work on the rest of the spec

**Comment by ffissore** [comment]
Since I don't want to ask you to share your pac file, can you please tell me which functions does it use, comparing it with the list available [here](https://web.archive.org/web/20070602031929/http://wp.netscape.com/eng/mozilla/2.0/relnotes/demo/proxy-live.html) ? (scroll down to *Predefined Functions and Environment for the JavaScript Function*)

**Comment by ffissore** [comment]
With 61626d4b17d3fe461240a396bc43bd751350f050 I've added support to PAC built in functions (all but time related). Wait for the next build from @ArduinoBot and please retry

**Comment by ffissore** [comment]
@McNeight FYI implementation should be complete. These messages from @ArduinoBot it's just me keeping this PR up to date with master branch

**Pull request merged**
