### PR TITLE
Allow the serial monitor to stay opened during upload, disabling it

### PR DESCRIPTION
**Pull request by Wackerbarth**
This is just a rebase of the code offered by @avishorp ( References #2180 )

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by hallard** [comment]
Works like a charm (windows 8.1 x64) 

this is a really, really great improvement and now solve me click on serial monitor after uplaod (I never succeeded to auto start it after upload) !!!!!

Thanks

**Comment by facchinm** [comment]
I really enjoy the "always on serial console" workflow, so I'm :+1: for the inclusion!

**Comment by PaulStoffregen** [comment]
Has anyone tested with Leonardo on the various operating systems?

**Comment by facchinm** [comment]
Leonardo on Linux is ok, Due's Native port get completely broken... 
Good point @PaulStoffregen ! Maybe this feature needs a little more analysis :smile:

**Comment by ffissore** [comment]
Tried with a Uno, a Leonard and a Due on both ports and worked fine

**Comment by Wackerbarth** [comment]
I just rebased it again to keep the updates current.

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by hallard** [comment]
Would it be possible to integrate this feature in the official build ? would be easier for everyone not ?

thanks for this great feature

**Comment by ffissore** [comment]
Behavioural changes require users testing and approval. We are working on that

**Comment by hallard** [comment]
Thanks, Excellent.
I'm asking because I'm using it since 2 month without any issue. And as I'm also building arduino-esp8266 often, in this build based on official arduino IDE I'm missing this feature ;-)

**Comment by ffissore** [comment]
Yeah :)

**Pull request merged**
