### PR TITLE
Add Git to IDE

### PR DESCRIPTION
**Pull request by CarlosMiguelCuevas**
This pull request solve the issue #4387. It only allow to use commit and view the log. It is basic but it is what the issue asked for, also if this feature is available others might help in its develop.

### CODE REVIEW

**Comment by avargas-nearsoft** [comment]
LGTM!

**Comment by ivanebernal** [comment]
Implements commit and log, It's a good start.

**Comment by VladimirAkopyan** [comment]
So are we doing this or what?

**Comment by CarlosMiguelCuevas** [comment]
Hi @VladimirAkopyan , I'm not doing it, feel free to take the issue if you like, and make it happen

**Pull request closed without merging**
