### PR TITLE
Arduino IDE on High DPI (take 2)

### PR DESCRIPTION
**Pull request by cmaglie**
This is a follow up on @PaulStoffregen's ~~PR #2532~~(edit: wrong number) PR #2776 

- Rebased ~~#2532~~ #2776  on current master
- Added some hi-res images for the toolbar
- Factored out the formula to scale up dimensions

TODO / questions:

- The font of the menus and the textarea are not scaled as the rest of the GUI. Is this because the OS scales them automatically? Otherwise we should scale them as well.
- Add a "Scale interface for UHD displays" preference in the preferences dialog.
- The `gui.scalePercent` is now a theme preference (in theme.txt) but I'm wondering if this should really be a general preference (in preferences.txt) because screen scaling doesn't seems related to the theme

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
The setting in theme.txt was a simple hack meant to eventually be replaced by a proper preference or automatic detection of the screen DPI from the operating system.

**Comment by elFallino** [comment]
Font size is scaled by the operating systems decoration manager / window manager while everything else is hardcoded info the IDE. 
Some things this patch is scaling could be done better by using proper Java Layout Managers , others need to be scaled (like all the bitmaps).

Automatical detection of screen resolution would be nice, but there is no common way to do so for all kinds of operating systems and window managers.

A good way could be a scaling option in preferences (e.g. a slider or drowdown in 25% steps Form 75% up to 400% or so).
Scaling the bitmaps is an issue, too. If they are scaled up to 400% or worst: scaled using an odd factor like 275%, they look pretty ugly. Pauls idea for that was to switch to high res bitmaps if scaling factor exceeds, lets say, 200% (rendering vector graphics would be an alternative).

**Comment by lmihalkovic** [comment]
The path i chose for the toolbar bitmaps was to replace them with java code generated from SVGs using a tool somewhere on github (described in #4196)

**Comment by lmihalkovic** [comment]
Each platform has a way to find out their scaling ratio, and the codebase already has the Platform class to abstract this kind of underlying API differences.

**Comment by cmaglie** [comment]
This last version includes:
- a new preference for setting scale that ranges from 100% to 200% (less than 100% is useless more than 200% is huuuge IMHO I see that most apps that allows interface scaling have the same range)
- now the resource images are vectorial SVG
- there is an "Autodetect" checkbox, this is a placeholder for an eventual future DPI-detection subroutine, for now it defaults to 100%.

Testing welcome!

/cc @00alis

**Comment by lmihalkovic** [comment]
You know that now that you converted the res to SVGs it is easy to generate java code for Icon subclasses?! Then you can cleanup the toolbar code (dont have to but it would help with making a Tool2 interface that would allow button contributions for eg) and eliminate batik

**Comment by elFallino** [comment]
Imagine a 15 Inc 4k (UHD) screen and 200% isn't huge. So please add some more scaling factors >200%.
There are already 5K displays and those high DPI displays will enter the consumer sector more and more.
Do not build-in unneccessary restrictions that will come up soon. ;)

**Comment by wishAI** [comment]
Unfortunally,it doesn't work on my surface pro 4 no matter how I change the "gui.scale" in the preferences.txt . Also , the links of the old versions doesn't work and I can't test it.

**Comment by cmaglie** [comment]
> no matter how I change the "gui.scale" in the preferences.txt

uhm, that's really weird, have you tried to change the value from the preference panel instead of changing preference.txt?

**Comment by cmaglie** [comment]
prefs

**Comment by elFallino** [comment]
It is working for me, using preferences window (Windows 10).

**Comment by wishAI** [comment]
I change it in the panel and it works , thank you.

**Comment by choidamdam** [comment]
@cmaglie
> more than 200% is huuuge

I'm using Dell Inspiron 15 7548 laptop and recommended display scaling (the default one) is 250% on Windows 10. Maximum scaling is 350% on my display settings.

**Comment by cmaglie** [comment]
Updated the scale range up to 400%

**Comment by jem-green** [comment]
Icon scaling works as expected while dragging the application across multiple monitors in windows 10

**Comment by jem-green** [comment]
Ok next is message windows being too small to read !
capture

**Comment by jem-green** [comment]
even smaller !
capture

**Comment by jem-green** [comment]
Double splash window at start-up is this normal?
capture

**Comment by jem-green** [comment]
And possibly finally can we scale the window size along with the preferences ?
capture

**Comment by cmaglie** [comment]
@jem-green thanks very much for the feedback, I'll try to address these issues!

**Comment by SuperBonny** [comment]
The tab bar reaches 3000px and doesn't scale higher
2016-01-21-183636_3840x2160_scrot

**Comment by elFallino** [comment]
Yes, its size is fixed in Code.
My original patch included scaling this one, too.

A better solution would be to use a layout manager other than the Null Layout Manager, but this would include a lot of work. I am not sure cmaglie would want to do this alone.

**Comment by WayneB2** [comment]
Thanks for working on this. It appears to be working for me.
I downloaded PR-4376-BUILD-483.windows.zip.  (Arduino 1.6.8)
I have a Surface Pro 4 i7 2736x1824 resolution running Windows 10
Checking "Auto" did not work. But unchecking Auto and setting scaling to 200% and font to 28 works well for me.
A popup occurred shortly after starting Arduino IDE saying there are updates available for libraries(I think).
It was too small to read. I was barely able to click the "X" to close it.

**Comment by nmaggioni** [comment]
Same issues of @WayneB2 on a Dell XPS 13.

**Comment by elFallino** [comment]
As I initially wrote the patch (Paul Stoffregen reviewed it, made it 
better and posted it to github - so many thanks to him) there was no 
Board Manager, so this patch does not affect it. But the additionally 
code should be easy. 
 
The point of this patch is, that you grap the GUI items that need to be 
scaled and -instead of fixed values for its size- it takes this fixed 
values and multiplies them with the scaling factor. Pretty simple, 
pretty unflexible - but at least the easiest solution. The disadvantage 
is, as you see, that you need to change every GUI item that does not 
scale by itself because its size is fixed or the Swing Layout Manager 
does not scale it automatically. 
 
Unfortunately, the GUI is build upon the Null Layout Manager that 
relies on fixed sizes - wich was okay as there was no highDPI screen 
"invented" yet. 
Changing it all would be a task that one person cannot solve. 
 
 
 
 

Ein Sun, 24 Jan 2016 10:26:00 -0800, Niccolò Maggioni  schrieb:

       Same issues of @WayneB2 on a Dell XPS 13. 
—
Reply to this email directly or view it on GitHub. 

   *

________________________________

**Comment by WayneB2** [comment]
Again, thanks for this patch. It makes Arduino on my Surface Pro useable.
Even though there are pop-up windows that are too small to read, I can work around that by using the Windows 10 Magnifier ("Windows Key" + "+" to read the popup, "Windows Key" + "-" to return to 100%)
This patch provided the solution that made the icons and menu items on the IDE scalable, and therefore the IDE functional on high DPI screens.
So I encourage you to put this patch into the next version of Arduino.

**Comment by cmaglie** [comment]
I've pushed another round of patch, this time:
- the Boards/Library managers should be scaled as well
- the "double splash screen" on windows should be fixed (though the splash screen is not scaled, sorry, I've not found a reliable way to do it)
- the editor font is scaled together with the interface, this means that if you set a scaling of, say, 150% and the font is set to 12 then the rendered font on the editor will be 18 (150% of 12), this means that you should first set the scaling, check the result and adjust the font size afterwards if it still doesn't match the desired size.
- notification pop-up is scaled too

**Comment by WayneB2** [comment]
Thanks. I would like to test this, but I am new to GitHub and this forum and don't know how to locate the latest patch. 
I tried clicking on "Release 1.6.8" in "cmaglie added this to Release 1.6.8 milestone 2 hours ago", but the code tab zip file does not appear to be a complete build.
Could you please show me how to access it, or provide a link like ArduinoBot did 14 days ago for the first patch.
Thanks...Wayne

**Comment by sandeepmistry** [comment]
@ArduinoBot build this please

**Comment by sandeepmistry** [comment]
@WayneB2 Arduinobot was having some issues earlier, a new build is available now in the comment above this one.

**Comment by WayneB2** [comment]
@cmaglie @sandeepmistry 
I tested Arduino-PR-4376-BUILD-494-windows on a Surface Pro 4 2736x1824 196dpi Windows 10
The splash screen being small is no problem. You can see it scaled properly with Help-About
Everything worked for me except Serial Monitor output text size and the Automatic check box.
I tried checking the Interface Scale Automatic check box, but it did not appear to do anything.
I settled on Editor Font 14, Automatic unchecked, 200%.
I opened Library Manager and updated some libraries. Everything was very readable.
I ran a sketch to print to Serial Monitor. 
The output area is still too small. That font did NOT scale together with the Interface Scale of 200%
Everything else (including the input/Send area) was very readable.
I am very happy with what you have done!

**Comment by mhdawson** [comment]
I tried the latest windows nightly and also did not see the option to scale.  I'd also like a pointer to a build I can test.  I have  a 13.3" 4k display I'd like to try it out with.

**Comment by cmaglie** [comment]
@WayneB2 I've pushed a fix for the serial monitor scaling too, hopefully this is the last one.

@WayneB2 @mhdawson @ramigrafx
ArduinoBot is creating a new test build of the Arduino IDE, it will post a new message here with the link to download in a couple of minutes.

**Comment by WayneB2** [comment]
@cmaglie 
Thank you. 
I tested Arduino-PR-4376-BUILD-494-windows on a Surface Pro 4 2736x1824 196dpi Windows 10 
Serial Monitor scaling of the text output area(via % in preferences) is working properly together with Editor Font size. The text "send" box (input) area does not seem to scale, and Editor Font does not change it, although it is readable at about 12 font. That seems reasonable, since it is a fixed size text box. 
Great job! Thanks again.

**Comment by Sembazuru** [comment]
Thank you for your hard work on adding the scaling to the user interface.
Now, if you could take it away from something... namely the scaling of the font size when printing. Thanx.

(Future feature request would be to add more options to the printing, but that is all out of scope here.)

**Comment by DanChesher** [comment]
Tested arduino-PR-4376-BUILD-496-windows on a Toshiba Satellite S55t-C5325-4K, 3840x2160 resolution, Windows 10. Works great! Thanks so much for making these changes.

**Comment by cmaglie** [comment]
@Sembazuru 
yes, the print function needs a bit of overhaul. The issue you reported AFAIU is old and not caused by this pull-request (even if the hi-dpi patch make it worse). I see that you already opened another issue, let's continue the discussion there.

**Comment by Sembazuru** [comment]
Ok. Sounds good. I just downloaded the most recent nightly (dated 2016-02-19T05:41) and the merge seems stable so far.

**Comment by jordansissel** [comment]
Success! I am using Arduino 1.6.8 and can confirm that the interface scaling preference works well for me (Windows 10)

Thank you! :heart:

**Comment by lorenzoromagnoli** [comment]
@cmaglie I can see that you added the 2x sized image,
 but it doesn't seem to be used and the splash screen still looks bad on my macbook retina display.
 https://github.com/arduino/Arduino/commit/328d3b6354b1ffd048d7ebe2bc3ef81afa0481fe

**Comment by tobsen** [comment]
Same here on a iMac retina, I also tried the nightly.

bildschirmfoto 2016-05-21 um 15 51 55

**Comment by andypiper** [comment]
What's the current story with the splash screen, toolbar icons, and the text in editor tab titles on OS X? Everything else looks nice and smooth, but those items seem to be scaled from low-res?

**Comment by edgimar** [comment]
I'm using version 1.6.12 of the IDE under Ubuntu 16.04 and Java 1.8.0_101.  When the interface scale is set to 200%, the editor window and tab (and status window) are properly sized on my display, however, the settings window, menus, and several other dialogs are still not scaled (text is very tiny).

**Comment by avastmick** [comment]
Windows 10 Dell XPS 15 9550 3840x2160 resolution. 

Generally the UI is fine and scales okay, but only once I set the scaling to 300% so the font size is easily readable. The pop-up screens are mangled and unusable, however.



Any ideas on how to be able to see pop-up screen like this?

**Comment by bbulkow** [comment]
Using 1.8.8 from the windows store.

Usable but not great.

The menu items aren't scaled.

The scaling set in the Window 10 UI isn't obeyed. All my other programs look at the scale factor I have set for that monitor, so when I drag a window from monitor to monitor, it rescales according to the scale factor of that monitor.

**Comment by tobia** [comment]
Does anybody have any workaround for telling Java how much to scale the default AWT elements, or whether to scale them at all?

I'm on a 125% HiDPI monitor. I have set X11's resource correctly to `Xft.dpi: 120` (96 × 1.25) but **Arduino (or Java) seem to detect a 200% HiDPI setting** from who knows where. I fixed the main interface using the "Interface Scale" preference, but I cannot find a way to scale the menus.

Is there an environment variable, Java property, or any other hack to force the AWT scaling factor, or even to disable it at all? Given the choice, I would prefer my menus to be 20% smaller, rather than 60% bigger.

Related to #6472

arduino_menu

**Comment by s-light** [comment]
found a workaround posted in [#9170](https://github.com/arduino/Arduino/issues/9170#issuecomment-583397780)
basically create a custom `.gtkrc-2.0` file with font size you like and start arduino with this file:
`GTK2_RC_FILES=my_arduino_gtkrc-2.0.conf arduino`

**Comment by Feromrk** [comment]
the workaround from @s-light didn't work for me (manjaro linux with kde). The menu bars still stayed ultra small.
Changing `GDK_SCALE` as @tobia  suggested worked! Note that it accepts only integer values (float doesn't work, so I had to set it to 2, instead of 1.5)

**Pull request merged**
