### PR TITLE
Prebuild hook in new compiler

### PR DESCRIPTION
**Pull request by Wackerbarth**
The new compiler dropped the prebuild hook

### CODE REVIEW

**Comment by ffissore** [comment]
No it didn't: see this [line of code](https://github.com/arduino/arduino-builder/blob/master/src/arduino.cc/builder/container_setup.go#L44). Can you provide a platform.txt that specifies them?

**Comment by ffissore** [comment]
Maybe that's the wrong place for executing that module and it should be moved down in the call chain

**Comment by ffissore** [comment]
Yes indeed. My fault. Fixing right now

**Comment by ffissore** [comment]
Fixed with 21ada82971de520d358fd3fd90e36b8693863cbb. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by Wackerbarth** [comment]
@ffissore -- Sorry, but you "fix" doesn't work. 
Please re-open this PR.

(I just recompiled it myself after updating my local repository)

From my platform.local
```
compiler.cpp.extra_flags=-D USE_AUTOMATIC_VERSIONING
build.custom_bin.path.macosx=/usr/local/bin/
recipe.hooks.prebuild0.pattern=mkdir -p "{build.path}/sketch/"
recipe.hooks.prebuild1.pattern={build.custom_bin.path}generate_version_header_for_marlin "{build.source.path}" "{build.path}/sketch/_Version.h"
```
Note that the prebuild0 recipe was just added because the target area doesn't yet exist when my patch gets executed.

generate_version_header_for_marlin is a simple bash script:
The significant part of it is
```
DIR=`dirname $1` export DIR
OUTFILE="$2" export OUTFILE
echo "" >>"$OUTFILE"
```
and other lines that build the useful contents of the _Version.h file

And that file is expected because the headers have a
```
 #include "_Version.h"
```

So, I expect my hook to be called before the preprocessor runs.

**Comment by ffissore** [comment]
You're right. Bug is that in looking for the hooks I forgot to prefix "recipe.". Fixing right now

**Comment by NicoHood** [comment]
May anyone explain me the feature you are talking about? I am interested and  I'v never heard of that, sorry.

**Comment by ffissore** [comment]
Another fix is available with hourly builds http://www.arduino.cc/en/Main/Software#hourly. Please give it a try

**Comment by Wackerbarth** [comment]
This time I think you got it.

**Comment by Wackerbarth** [comment]
@NicoHood -- As with a number of build procedures, it is often useful to have a custom operation performed at the beginning of the build process.

I utilize this hook to run a script which uses `git describe` to extract information from the currently checked out version of my repository and create a header file which I then include in the compiled sources to make available, at run time, a version identification string.

The advantage in doing so is that each build is uniquely identified without the necessity of my manual updating of that identifier string.

You can look in my comments (above) to see an example.

**Comment by thaanstad** [comment]
I believe this bug has reappeared.  I am compiling for the adafruit NRF52 and the build.source.path is pointing to the .ino file.

platform.txt file:
`recipe.hooks.sketch.prebuild.0.pattern= C:\Program Files (x86)\Arduino\increment.bat {build.path} {build.source.path} {build.project_name}`

build output:
`recipe.hooks.sketch.prebuild.0.pattern
C:\Program Files (x86)\Arduino\increment.bat C:\Users\thaanstad\AppData\Local\Temp\VMBuilds\RTCSleepTest\adafruit_feather52\Release C:\Users\thaanstad\Desktop\ArduinoSketchLocationWC\trunk\RTCSleepTest\RTCSleepTest.ino RTCSleepTest.ino
	Process: C:\Program Files (x86)\Arduino\increment.bat C:\Users\thaanstad\AppData\Local\Temp\VMBuilds\RTCSleepTest\adafruit_feather52\Release C:\Users\thaanstad\Desktop\ArduinoSketchLocationWC\trunk\RTCSleepTest\RTCSleepTest.ino RTCSleepTest.ino
The system cannot find the file specified`

**Comment by facchinm** [comment]
Hi @thaanstad ,
which IDE version and NRF core are you using?

**Comment by thaanstad** [comment]
facchinm,

I am using Arduino 1.8.5 along with visual micro however the output is from a compile in the Arduino IDE.  I am using Adafruit's NRF52 0.8.4 core downloaded from boards manager.  I can provide files or portions thereof if needed for debugging.

Thanks!

**Pull request closed without merging**
