### PR TITLE
New Editor (based on RSyntaxTextArea ) - 1.6.4

### PR DESCRIPTION
**Pull request by ricardojlrufino**
Arduino New Editor
===========================
These amendments replace the old editor for the RSyntaxTextArea, which is an updated library and evolves separately

It is considered a prerequisite to integrate Autocomplete (https://github.com/arduino/Arduino/issues/849)

Improvements and adjustments
=====================
[x] Syntax highlight (using xml files)
     [ ] load the list dynamically (is currently fixed in the code)
[x ] Code Folding
[x] Add 'Auto Format' to Editor context menu
[x] Removed menu: Find using selection (not required!)
[x] Open Reference and Links using CTRL + Click

[x] Preferences for syntax highlighting theme
[x] Muli-line ident using TAB
[x] Automatic closing doc/comment block 
[x] [Linux] Installation Script  that creates shortcuts on the menu and desktop (with SplashScreen)
[x] [Linux] Best ICON for Alt+TAB
[x] [Linux] fix CTRL+'/' not working (need test on MacOS !)
[x] FIX: Ugly Icon and Name on Linux (ALT+TAB  Window)

New Shortcuts
================
- HOME: toggles between first character on line and first non-whitespace character on line.
- INSERT: toggles between insert and overwrite modes.
- TAB / SHIFT + TAB: Increase / Decrease Indentation
- Alt + UP/DOWN : Move the current line up and down, respectively.
- Ctrl + / : tootle comments
- Ctrl+TAB / Control+SHIF+TAB: Change TABS  (BUG: Control+SHIF+TAB not work on linux)
- Ctrl+D: Delete current line
- Ctrl+DELETE: deletes all text between the caret and the end of the current line.
- Ctrl+J: joins lines.
- Ctrl+Z: is undo and Ctrl+Y is redo.
- Ctrl+Up and Ctrl+Down: shift the visible area of the text area up and down one line, respectively.
- F2 and Shift+F2: moves to the next and previous bookmarks,respectively.
- Ctrl+arrow keys: Better keyboard navigation 

Tests
=======================
[x] comment / uncomment using shortcuts, menu, popup menu
[x] Copy to HTML and Forum
[x] Auto Format
[x] Find using selection (shortcut CTRL+F)
[ ] Fix Encoding & Reload (what is this ?)
[x] Find in Reference
[x] Open URL (from comment's)
[x] Add new Tab
[x] Open / Save sketch with multiple files
[x] Highlight compilation errors (even in other tabs)  
[x] Undo / Redo (even in other tabs)
[x] Undo / Redo in Context Menu (even in other tabs is consistent)
    - Improved Ctrl-z system (before was 1 for 1 character, so boring)
[x] Keywords.txt  (including libraries)
[x] Keep Selection / Cursor when switch between Tabs
[x] Auto-close / Identation brackets in if/method/etc..
[x] Auto ident on new Line.
[x] Menu shortcuts (tests)
[x] Syntax coloring: use the same colors (only a small modification)
[x] Preferences: Show Lines Numbers

screenshot

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by duff2013** [comment]
I like the update! But code folding doesn't seem to work in the osx build? Its not selectable?
screen shot 2015-04-23 at 11 28 18 am

**Comment by 00alis** [comment]
**A really tiny detail**, on Retina displays the Sketch name on the Tab is pixelated, while all the other text everywhere else is correctly rendered. What could be the cause of it?

**Comment by ricardojlrufino** [comment]
@duff2013 try now ;)

**Comment by ricardojlrufino** [comment]
@00alis you can attach a screenshot ?!

**Comment by ricardojlrufino** [comment]
@ArduinoBot build this please

**Comment by damellis** [comment]
There are a lot of changes here that may or may not be considered improvements, depending on your expectations. (Note that the following is mostly Mac centric, although I'm guessing there may be similar issues on other platforms.)

For example, this changes the behavior of Command-Left to go to the first non-whitespace character of a line instead of the first character. This corresponds with Processing's behavior but differs from the Mac default (e.g. in Xcode). Similarly, selecting text and hitting tab in Xcode seems to behave like a normal character entry (the selected text is replaced with the typed tab character), whereas other applications (like Processing) indent selected lines when you press tab. 

Similar comment for Command-F using the current selection as the find text. This is non-standard behavior on Mac, which has a separate keyboard shortcut (Command-E) to search for the currently-selected text.

The Alt-Up and Alt-Down behavior (moving the current line up or down) is something I've never experienced in another application and wouldn't expect to happen here. Similar with Command-J (outside of vi). 

The syntax highlighting look different. I believe we just deliberately chose colors for various kinds of keywords; do we want to change them again? The default font also looks different. Again, who should be deciding on these aspects?

This patch also seems to break some things. I can no longer click on links to open them, for example. I also can't Alt-Backspace to delete the word preceding the cursor (a standard Mac behavior).

Are there improvement here that I'm missing? Otherwise, this seems to just change a lot of things without necessarily making anything better.

**Comment by duff2013** [comment]
@damellis
I really have to disagree on some this, there are many new enhancments that I consider quite nice. The UI is really in need of some features that you totally disregard i.e. code folding, error highlighting,  unreadable error color, move line (Alt up/down), etc.. I really think this is good step forward for a more advanced UI in my opinion though I'm sure there is major room for UI improvement still.

**Comment by ricardojlrufino** [comment]
This improvement is mainly focused on replacing the old editor at RSyntaxTextArea.

This has been proposed numerous times, the RSyntaxTextArea is a component that possesses enough interesting features (that were not explored in this modification, still ...), and evolves independently of the Arduino way.

And it is one of the main points is to integrate **Autocomplete**
3 years waiting, I took the attitude and did.... https://github.com/arduino/Arduino/issues/849
However had little feedback and it seemed that it was not a priority (I disagree)

Documentation of libraries in the Editor : https://github.com/arduino/Arduino/issues/2692

Many of the things that you said was OSX details, I did not know, so there would have to meet these requirements. Could you help!

**Comment by PaulStoffregen** [comment]
@ArduinoBot build this please

**Comment by 00alis** [comment]
Here is the screenshot, even though it is not really helpful on non-retina displays. Anyway text should not pixelate at all.
screenshot 2015-04-24 10 13 12

@damellis @ricardojlrufino 
> The syntax highlighting look different. I believe we just deliberately chose colors for various kinds of keywords; do we want to change them again? The default font also looks different. Again, who should be deciding on these aspects?

We recently updated the syntax highlight of the Arduino code to match the 3 syntax groups we have (Functions, Structure and Variables). We are going to keep these new colors and keywords, because they have been carefully tested and approved. I don't see a difference in the default font, @damellis could you provide more details?
And I am taking care of this color highlight change, so let me know if you have any feedback on it. A couple of weeks ago we fixed the color of the error messages (was too dark).

Thanks!

**Comment by ffissore** [comment]
@ricardojlrufino I'm working on some of the reported issues while constantly merging with master. I'm pushing my changed onto https://github.com/ffissore/Arduino/tree/1.6.4-new-editor

**Comment by ffissore** [comment]
ATM I'm working on restoring keywords.txt color mappings

**Comment by ricardojlrufino** [comment]
@ffissore  Okay, I'll follow in your branche
---
The adjustments made in colors, was to maintain consistency with the look of the IDE, I think that it was good ...
If you need to change in fact, then we can turn the current on a new theme: 'bluesky'

**Comment by ricardojlrufino** [comment]
@ffissore @00alis 

TIP: To test color changes do not need restarting the IDE, just change the file and save your preferences again

**Comment by ffissore** [comment]
@ricardojlrufino I've just rebased and force pushed on my branch https://github.com/ffissore/Arduino/tree/1.6.4-new-editor

In order to keep this PR in sync, please:
```
#fetch all modifications occured in the meanwhile
git fetch --all
#rebase your local copy (supposing remote is called upstream)
git rebase upstream/master
#merge my modification (supposing remote is called ffissore)
git merge ffissore/1.6.4-new-editor
#force push onto your branch
git push -f origin 1.6.4-new-editor
```
ArduinoBot will take care of building a fresh IDE

**Comment by ffissore** [comment]
As you can see, I've reverted two commits because they were either useless or changing a well documented/known behaviour/look&feel
I've also removed theme selection since we need to accustom to this new editor before squeezing every bit out of it.
I've also restored keywords.txt and theme.txt role into ruling which colors get used where, because this also is a known/documented feature

**Comment by damellis** [comment]
Trying ffissore/Arduino/tree/1.6.4-new-editor, here are a few comments:

Alt-Backspace (to delete the word preceding the cursor) doesn't work. I think this is a Mac-specific keyboard shortcut, but it does work in the current 1.6.3 release. 

URLs in comments are no longer clickable. 

Code-folding isn't really useable unless line numbers are visible. Maybe if code-folding is enabled, the column next to the line numbers showing the code-folding icons should be visible, even if the line numbers themselves aren't?

I like the way that code-folding in Xcode shows the closing terminator (see screenshot). How hard would it be to do something like that?

screen shot 2015-04-27 at 3 28 28 pm

I find the Alt-Up and Alt-Down (to move the current line up and down) disconcerting. Also, on Mac those keyboard shortcuts have a different meaning (move up or down a paragraph). I'd suggest removing the line-moving behavior, at least on Mac.

Command-Up and Command-Down should go to the top or bottom of the editor on Mac, although this doesn't work in 1.6.3 either.

This version changes the behavior of the Command-Left key to go to the first non-whitespace character in the line instead of the first character in the line. I don't think there's a clear better option here (some people prefer one and some people the other) but this is a change that may trip up people who are used to the other behavior. (Of course, the current behavior may trip up people that are used to the opposite.)

In this version, the font and colors look the same as 1.6.3.

**Comment by damellis** [comment]
Also, on Mac the standard is that Command-E uses the current selection for the find text, and that Command-F re-opens the search dialog without changing the find text to the current selection. It would be nice to stick to the standard.

**Comment by ricardojlrufino** [comment]
@ffissore I did the merge !

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by duff2013** [comment]
Latest Build-251 (osx) hyperlinks are still not clickable, a.k.a not going to the website.

**Comment by ricardojlrufino** [comment]
There are two alternatives:
- Right click -> Open URL
- Ctrl + Click

But I'll see how to enable by default ...

**Comment by duff2013** [comment]
ok i see, thanks, but on osx ctr + click also opens the drop down menu before going to the web address, this will be confusing to users for sure, i think being able to just left click a link should be implemented. I would do pull myself if I knew how to do this java stuff but i don't so i will just be beta tester:)

**Comment by duff2013** [comment]
so I'm seeing other issues with hyperlinks with this build, if right click an choose open url from the drop down or ctr+click i get this error from ide with this sketch where i copy and pasted a url as comment. After this the IDE acts very sluggish and weird things happen.
screen shot 2015-04-28 at 2 03 05 pm

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at processing.app.macosx.Platform.openURL(Platform.java:129)
	at processing.app.Editor$23.hyperlinkUpdate(Editor.java:945)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.fireHyperlinkUpdate(RSyntaxTextArea.java:849)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.access$600(RSyntaxTextArea.java:138)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea$RSyntaxTextAreaMutableCaretEvent.mouseClicked(RSyntaxTextArea.java:3123)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6528)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: The file: https:/github.com/arduino/Arduino/pull/3019 doesn't exist.
	at java.awt.Desktop.checkFileValidation(Desktop.java:210)
	at java.awt.Desktop.open(Desktop.java:270)
	... 42 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at processing.app.macosx.Platform.openURL(Platform.java:129)
	at processing.app.Base.openURL(Base.java:2056)
	at processing.app.Editor$59.actionPerformed(Editor.java:2864)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: The file: https:/github.com/arduino/Arduino/pull/3019 doesn't exist.
	at java.awt.Desktop.checkFileValidation(Desktop.java:210)
	at java.awt.Desktop.open(Desktop.java:270)
	... 46 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at processing.app.macosx.Platform.openURL(Platform.java:129)
	at processing.app.Editor$23.hyperlinkUpdate(Editor.java:945)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.fireHyperlinkUpdate(RSyntaxTextArea.java:849)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.access$600(RSyntaxTextArea.java:138)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea$RSyntaxTextAreaMutableCaretEvent.mouseClicked(RSyntaxTextArea.java:3123)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6528)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: The file: https:/github.com/arduino/Arduino/pull/3019 doesn't exist.
	at java.awt.Desktop.checkFileValidation(Desktop.java:210)
	at java.awt.Desktop.open(Desktop.java:270)
	... 42 more
```

**Comment by ricardojlrufino** [comment]
@ffissore  please leave different colors for the numbers, it helps ;)

**Comment by ricardojlrufino** [comment]
@duff2013 hyperlinks enabled by default, no longer need the Ctrl

**Comment by ricardojlrufino** [comment]
An **error** also occurs when you **add a blank space before the URL** (which is already in the text)

Something related to management PdeKeywords.keywordTokenType

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 62
	at org.fife.ui.rsyntaxtextarea.TokenMap.getHashCode(TokenMap.java:202)
	at org.fife.ui.rsyntaxtextarea.TokenMap.get(TokenMap.java:125)
	at processing.app.syntax.PdeKeywords.getTokenType(PdeKeywords.java:169)
	at processing.app.syntax.SketchTokenMaker.addToken(SketchTokenMaker.java:54)
	at org.fife.ui.rsyntaxtextarea.TokenMakerBase.addToken(TokenMakerBase.java:108)
	at org.fife.ui.rsyntaxtextarea.modes.CPlusPlusTokenMaker.addToken(CPlusPlusTokenMaker.java:1855)
	at processing.app.syntax.SketchTokenMaker.addToken(SketchTokenMaker.java:50001)
	at org.fife.ui.rsyntaxtextarea.modes.CPlusPlusTokenMaker.addToken(CPlusPlusTokenMaker.java:1839)
	at org.fife.ui.rsyntaxtextarea.modes.CPlusPlusTokenMaker.yylex(CPlusPlusTokenMaker.java:2303)
```

**Comment by ricardojlrufino** [comment]
Link *https://*github.com/arduino/Arduino/pull/3019  is working on linux
Try the same ink the old IDE, maybe the error is here: processing.app.macosx.Platform.openURL

**Comment by ffissore** [comment]
@ricardojlrufino things went really bad with the merge. Half my commits were trashed. I've remade the branch and force pushed onto https://github.com/ffissore/Arduino/tree/1.6.4-new-editor
Please execute the following commands
```
git fetch --all
git checkout master
git branch -D 1.6.4-new-editor
git checkout ffissore/1.6.4-new-editor
git branch --set-upstream-to=origin/1.6.4-new-editor
git push -f origin 1.6.4-new-editor
```

**Comment by ffissore** [comment]
@damellis my force pushed branch also contains a fix to the bug you found about code folding not showing when line numbers were disabled

**Comment by PaulStoffregen** [comment]
Looks like this isn't going to make it into the 1.6.4 release, is it?

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by PaulStoffregen** [comment]
I'd really like to work on building some features on top of this work.... so my hope is this can get merged shortly after 1.6.4 releases.

Let's not hold up merging and allowing maximum time for community testing and feedback only because a couple keyboard shortcuts are missing on 1 platform.

**Comment by ffissore** [comment]
Rebased and merged. See https://github.com/arduino/Arduino/commits/5bc6cee1185cf780a6e0445e43accf5842f515e8
Mac keyboards shortcuts issue will go into a separate issue

**Comment by j-s-com** [comment]
The bug, that no UniCode Character is accepted when typed in the editor is still present in 1.6.4. You told me via mail that there is a new editor but the bug is the same. No äöü are accepted. Who tested this?

**Comment by ffissore** [comment]
I haven't told you it was solved in 1.6.4. Indeed the fix is in the [hourly build](http://www.arduino.cc/en/Main/Software#hourly) and will be released with 1.6.5

**Comment by j-s-com** [comment]
Hello & thanx for the information.

It is always a little bit difficult for me because I use a Teensy 3.1 and
every time I install a new arduino I have to wait until the right Teensy
patch is available. I have very large projects and work with a Due, a Mega
2560 and a Teensy.

Best regards

Jörg Schreiber

-- 

Jörg Schreiber Consulting
Straßburger Str. 320
46045 Oberhausen

Telefon: 0208-880710
Telefax: 0208-880719
Mobil  : 0151-23000449

Ust.-ID: DE212722362

http://www.jsob.de/
EMail: js@jsob.de


Von:  Federico Fissore <notifications@github.com>
Antworten an:  arduino/Arduino
<reply+00b75e29f6dcfe8ccd337d45e0fda10ee2aead05ef98ec0092cf00000001116966609
2a169ce042f7f7a@reply.github.com>
Datum:  Dienstag, 12. Mai 2015 08:57
An:  arduino/Arduino <Arduino@noreply.github.com>
Cc:  Jörg Schreiber <js@jsob.de>
Betreff:  Re: [Arduino] New Editor (based on RSyntaxTextArea ) - 1.6.4
(#3019)


I haven't told you it was solved in 1.6.4. Indeed the fix is in the hourly
build <http://www.arduino.cc/en/Main/Software#hourly>  and will be released
with 1.6.5


Reply to this email directly or view it on GitHub
<https://github.com/arduino/Arduino/pull/3019#issuecomment-101158020> .

**Comment by j-s-com** [comment]
Hi again,

I have another problem for some time:

I would like to make optional #includes, means on teensy I would like to
include i2cr3 and on Mega wire.h but this does not work. All #includes are
seen by the preprocessor, regardsless if the are in #if #endif or not. All
other things I need work in the #if/#endif.

The sense behind this is having a platform independent library for my
sketches.

Do you have a suggestion?

Best regards

Jörg Schreiber

-- 

Jörg Schreiber Consulting
Straßburger Str. 320
46045 Oberhausen

Telefon: 0208-880710
Telefax: 0208-880719
Mobil  : 0151-23000449

Ust.-ID: DE212722362

http://www.jsob.de/
EMail: js@jsob.de


Von:  Federico Fissore <notifications@github.com>
Antworten an:  arduino/Arduino
<reply+00b75e29f6dcfe8ccd337d45e0fda10ee2aead05ef98ec0092cf00000001116966609
2a169ce042f7f7a@reply.github.com>
Datum:  Dienstag, 12. Mai 2015 08:57
An:  arduino/Arduino <Arduino@noreply.github.com>
Cc:  Jörg Schreiber <js@jsob.de>
Betreff:  Re: [Arduino] New Editor (based on RSyntaxTextArea ) - 1.6.4
(#3019)


I haven't told you it was solved in 1.6.4. Indeed the fix is in the hourly
build <http://www.arduino.cc/en/Main/Software#hourly>  and will be released
with 1.6.5


Reply to this email directly or view it on GitHub
<https://github.com/arduino/Arduino/pull/3019#issuecomment-101158020> .

**Comment by ffissore** [comment]
@j-s-com while I'm really happy to see you involved into the IDE development, please don't mix different issues into one. Issues are for bug and improvement proposal only. One issue, one bug/proposal. In your case, your issue is affecting [many users](https://github.com/arduino/Arduino/labels/Component%3A%20Preprocessor). Please consider searching for existing issues before posting new ones

**Comment by PaulStoffregen** [comment]
>I would like to make optional #includes, means on teensy I would like to
> include i2cr3 and on Mega wire.h but this does not work. All #includes are
> seen by the preprocessor, regardsless if the are in #if #endif or not.

This is issue #2792, and also this conversation:

https://groups.google.com/a/arduino.cc/forum/#!topic/developers/JwdS_1Y8o-4

**Pull request closed without merging**
