### PR TITLE
Update jmdns to 3.5.1

### PR DESCRIPTION
**Pull request by facchinm**
Evaluate if https://github.com/arduino/Arduino/pull/4482/commits/d403c9ae949765ac98956661c32ab4c304a9abd8 and https://github.com/arduino/Arduino/pull/4482/commits/944dcf10736d058a1cb3d349f83f0cce09c71f99 are needed to solve https://github.com/arduino/Arduino/issues/4569 or if updating to 3.5.1 is enough

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @docbender, could you test the build which will be produced on your PR with 5 network cards? Thanks a lot!

**Comment by docbender** [comment]
Hello @facchinm,
I tried new build, but it failed to start. Tested on 2 PC's. Both same. Here is program output:
```
Loading configuration...
Initializing packages...
java.lang.NoClassDefFoundError: javax/jmdns/ServiceListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at cc.arduino.packages.DiscoveryManager.<init>(DiscoveryManager.java:44)
        at processing.app.BaseNoGui.initPackages(BaseNoGui.java:495)
        at processing.app.Base.<init>(Base.java:257)
        at processing.app.Base.main(Base.java:140)
Caused by: java.lang.ClassNotFoundException: javax.jmdns.ServiceListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 more
```

**Comment by facchinm** [comment]
Sorry for the inconvenience, the Windows package was missing an entry in the classpath; I just pushed a commit to fix this, which should trigger a new build. Thanks again for testing!

**Comment by docbender** [comment]
Here are CPU tests with new build. Build 643 with 6 active network card:

image

Compared with Arduino 1.8.1 CPU utilization looks similar. I both cases one core is almost full utilized:

image

Here is another system (4 thread Core-i5) with 3 network cards. In a direct comparison, it seems that with the new nDNS load is same or a little bit higher:

image

**Comment by facchinm** [comment]
Thanks a lot for testing this, I was hoping that simply upgrading the library would solve the issue but I was wrong :slightly_smiling_face: I'm pushing some other commits to this repo to solve the high cpu usage once for all (by using some new features of jmdns)

**Comment by docbender** [comment]
Now it looks much better. Nice work. There are now peeks in 10s period and when network subsystem has changed.

image

**Comment by facchinm** [comment]
@me-no-dev @igrr would you mind testing this PR with ESP8266 and ESP32 boards advertising via mDNS? If you see no regression (or maybe an improvement) I believe we can merge this

**Comment by me-no-dev** [comment]
@facchinm will do right away on both ESPs :)

**Comment by me-no-dev** [comment]
@facchinm I can confirm no regression on ESP8266 and ESP32. I can also confirm lower load on  the network.
I've been waiting for a long time for this :) I even remember looking into it while working on the ESP OTA, but found the cause to be somewhere in the lib itself as I was seeing the same behavior on Android and Eclipse. I'll monitor the situation, but so far, so good :)
Great work!

**Pull request merged**
