### PR TITLE
Fix nextTab/prevTab selection logic

### LINKED ISSUE #5380: Edit > Find issues
Using Arduino IDE 1.6.12 Hourly Build 2016/09/14 08:20 with Windows 7 64 bit
- Create a sketch with 3 or more tabs.
- Add the text **findtext**(or any text you like) to each tab.
- Save the sketch.
- Close the sketch.
- Open the sketch.
- **Edit > Find > Find: > findtext**
- Check the **Search all sketch tabs** box

**Issue 1:**
- Click **Find** button repeatedly -The found text on all but the first tab is not highlighted. If you click on the IDE window(not on the editor area as this will cause it to be deselected) the highlight will appear. Once that has been done, the highlight will appear on that tab on subsequent finds. This is the reason the sketch had to be closed and reopened, because the process of creating the tabs/adding the **findtext** to each tab causes the highlighting to work correctly.

**Issue 2:**
-  Find goes through the tabs right to left instead of the previous left to right behavior.

**Issue 3:**
- **Replace with: > replaced**
- Click **Replace all**
- The **findtext** in the second tab was not replaced.

These issues don't occur with Arduino IDE 1.6.11 or previous

Please don't release Arduino IDE 1.6.12 before this issue is fixed. It's very important for **Replace All** to work reliably.

### PR DESCRIPTION
**Pull request by facchinm**
fixes #5380

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Hey, you're stealing my PR :-)

**Comment by matthijskooijman** [comment]
I stole it back, I replaced my commit with yours. Content is identical, but my commit message was a bit more complete :-)

**Comment by facchinm** [comment]
LOL :smile:

**Comment by cmaglie** [comment]
I've pushed some more commits that solves the highlight bug and fix another corner case with foldings.
There are also 2 other commits that simplifies a bit the find algorithm.

**Comment by matthijskooijman** [comment]
@cmaglie, awesome, thanks for digging into this. Commits look great to me, I especially like the long commit messages on the cleanup commits :-D

**Pull request merged**
