### PR TITLE
Set unused bits of extended fuse to 1

### PR DESCRIPTION
**Pull request by descampsa**
Avrdude has changed the way it handle unused bits in the extended fuse for atmega 328 and atmega 168, they are now at 1 instead of 0.
See http://svn.savannah.nongnu.org/viewvc?view=rev&root=avrdude&revision=1335 for more info.
This causes avrdude to fail when one try to write the fuse with the unused bits at 0, because the value it read back is not the same than the one it tried to write. This commit fixes the fuse value for all boards that use atmega328 or 168.

See also issue https://github.com/arduino/Arduino/issues/5175

I only tested that fix with a usbasp programmer on arduino uno, it would probably be good that someone test it with other programmer/board (especially one atmega168) to be sure.

Update: According to the discussion in https://github.com/arduino/Arduino/issues/5175 , the patch indeed fix the problem for Atmega328 with usbasp, USBtinyISP and ArduinoISP. 
A separate but related issue appears with AVRISP mkII programmer, but this issue can't be easily fixed in Arduino code alone, avrdude.conf has to be changed.

### CODE REVIEW

**Comment by per1234** [comment]
Just a clarification, I tested with **Tools > Programmer > Arduino as ISP**, which is an Arduino running the ArduinoISP sketch. I didn't test with **Tools > Programmer > ArduinoISP** because I don't own that programmer.

**Comment by per1234** [comment]
You missed one: https://github.com/descampsa/Arduino/blob/1e162f52d92282cd0dce7c828793b9a938d26547/hardware/arduino/avr/boards.txt#L459

**Comment by descampsa** [comment]
Yes, thanks, it's fixed.

**Comment by per1234** [comment]
I successfully tested Burn Bootloader on all ATmega168 based boards in this boards.txt using USBasp, Arduino as ISP, USBtinyISP, and Atmel AVRISP mkII(with https://github.com/arduino/avrdude-build-script/issues/2 applied).

**Comment by matthijskooijman** [comment]
This looks like a good change to me. I think it would be good if a second person would verify the new settings against the datasheet, to prevent accidental changes. And of course testing, I think @facchinm was planning to do some testing as well.

**Comment by descampsa** [comment]
@facchinm

Should'nt this patch be included in #5374?
It is not strictly essential, but currently the avrdude warning is printed at upload. 
Seems kind of strange to not fix our own warnings ;-)

**Comment by facchinm** [comment]
@descampsa 
we simply can't update the core this way because it would break backwards compatibility (in fact, this modification only works with avrdude 6.3). Updating the AVR core standalone (without the tools) on older installations is possible and would be much more difficult to solve (without patching avrdude 6.0.1)

**Comment by matthijskooijman** [comment]
@facchinm, huh? but a core / platform specifies what versions of the tool it needs in the JSON? Or did I misunderstand something here?

**Comment by matthijskooijman** [comment]
You mean when someone manually copies the arduino/avr directory out of git? That doesn't sound like a usecase we need to support?

**Comment by facchinm** [comment]
There were a couple of other cases which I can't remember right now, but I'm not saying we shouldn't merge this patch,I would only give give people some time to update their tools :smile:

**Pull request merged**
