### PR TITLE
Update AppStream XML metadata

### PR DESCRIPTION
**Pull request by mavit**
Support new fields coming soon to Gnome Software.

### CODE REVIEW

**Comment by probonopd** [comment]
Getting
```
E - arduino.appdata.xml:<root>
    The metainfo file uses an ancient version of the AppStream specification, which can not be validated. Please migrate it to version 0.6 (or higher).
```
when trying to validate the AppStream XML metadata currently in `master`using `appstreamcli`.

**Comment by probonopd** [comment]
But also the version in this PR does not validate:

```
$ appstreamcli --version
AppStream CLI tool version: 0.9.4

$ appstreamcli validate /home/me/Downloads/appdata.xml 
E - appdata.xml:arduino.desktop
    Invalid property for 'url' tag: "translate"

Validation failed.
```

**Comment by mavit** [comment]
The [appstream release notes](https://github.com/ximion/appstream/blob/master/NEWS) say that the `translate` `url` type was new in version 0.9.8.

**Comment by facchinm** [comment]
Can we close this and supersede in favour of #5892 ?

**Comment by mavit** [comment]
#5892 looks good to me.

**Pull request closed without merging**
