### PR TITLE
Replace jTouchBar jar with swing-only version

### PR DESCRIPTION
**Pull request by facchinm**
~~Fork here ATM (https://github.com/facchinm/JTouchBar)~~
Using jar from https://oss.sonatype.org/content/repositories/snapshots/com/thizzer/jtouchbar/jtouchbar/1.0.0-SNAPSHOT/  tracking https://github.com/Thizzer/jtouchbar/releases/tag/1.0.0-SNAPSHOT-20190121

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@facchinm works fine on my MacBook, my only suggestion is to rename the jar with an `-arduino` suffix and maybe the date for version as we are not using 0.1.0.

**Comment by sandeepmistry** [comment]
The new build with the 1.0.0 SNAPSHOT jar looks good here!

**Comment by ttveldhuis** [comment]
Just a small fyi: JTouchBar 1.0.0 has been released.

**Comment by sandeepmistry** [comment]
@ttveldhuis thanks for the heads up!

Closing in favour of https://github.com/arduino/Arduino/pull/8429, which uses JTouchBar 1.0.0.

**Pull request closed without merging**
