### PR TITLE
Using tabulation instead of white spaces for ide-1.5.x.

### PR DESCRIPTION
**Pull request by ghost**
Tabulator fix to preserve lifetime of backspace key.
ô.Ô

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by bxnc** [comment]
@ArduinoBot are you in winter sleep?

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by ffissore** [comment]
@bxnc build failed because of a network problem during upload. Retriggering

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by bxnc** [comment]
Setting "editor.tabs.expand=false" in preferences.txt changes the behavior of tabulation.
The build works.

**Comment by ffissore** [comment]
Became unmergeable. Closing

**Pull request closed without merging**
