### PR TITLE
TWI timeout

### PR DESCRIPTION
**Pull request by DanNixon**
Adds an iteration limit to the while loops in various ```twi_``` functions and resets TWI bus if limit is reached.
Stops entire microcontroller form hanging if for whatever reason the TWI bus fails.

### CODE REVIEW

**Comment by thirtythreeforty** [comment]
This needs to get merged, or something similar to it.  This bug just bought me an AVR Dragon to find the issue.

**Comment by DanNixon** [comment]
@thirtythreeforty I'll fix the merge conflicts when I'm back on internet that's fast enough to clone the ridiculously oversized repository.

I had completely forgotten about this considering I opened this over a year ago.

**Comment by PaoloP74** [comment]
News?

**Comment by wmarkow** [comment]
@DanNixon, you closed this pull request but it seems that your proposal have never been merged. Was there any particular reason behind this?

**Comment by DanNixon** [comment]
@wmarkow It sat for over two years with no activity.

**Comment by wmarkow** [comment]
Ok, I just thought that there was something wrong with your proposed fix. I'm facing the same problem with **Wire** library and adding some timeout feature would help for me. So I started to look for a solution and I have found you pull request. Actually I took some of your ideas to implement my own solution. Thanks.

**Comment by thirtythreeforty** [comment]
@wmarkow I can vouch that this solution works perfectly... we pulled this commit in, as-is, for a project a couple years ago.

**Comment by wmarkow** [comment]
Thank you guys for your input. It is good enough for me to know that this commit works nice.

**Comment by RalfvandenBurg** [comment]
I also used this fix, it should be included especially if you i2c bus isn't that good shielded.

**Comment by nothingface0** [comment]
I've also tested in sure-to-hang conditions (first by connecting CLK to ground and also in a system with very long I2C cables), and I can confirm that I've got several days uptime.

**Comment by ermtl** [comment]
It's been 9 FUCKING YEARS since that bug was first discussed (2011), countless people pulled their hair trying to understand why their Arduino was freezing, why would it work normally, then suddenly stop, a dozen of times, it's been raised in here, dozens of times people had been told to get lost, use something else, etc ...
#7328
#2418
#1842
#5249
arduino/ArduinoCore-avr#42
Google shows pages after pages of people getting started and who get discouraged by this elusive bug they don't understand. This runs totally contrary of what arduino is supposed to stand for.

If the fix was difficult, if it compromised compatibility or added other problem, it would be understandable, but it's not the case, all that shit is caused by those 2 damn lines of code that obviously can create an infinite loop if for some reason the read operation does not complete :

// wait for read operation to complete
while(TWI_MRX == twi_state){
continue;
}

Yes, I know, this state is not supposed to happen according to the I2C protocol, but guess what ? electrical glitches didn't get the memo.

Countless people, after losing hours or days kind of solved the issue either by making a modified version for themselves, or switching to another library, so there are several implementations of a timeout that are simple and would easily solve the issue.

But arduino developpers stubbornly refuse to fix it !

You think I'm rude ? After 9 years of giving the finger on this issue to the whole community for absolutely no reason, I couldn't care less.

How long before you close it again ?
Just be honest, and put a "fuck you all, WONTFIX" label on it ...

**Review by Helmutssp89 — CHANGES_REQUESTED** [review]
We

**Pull request closed without merging**
