### PR TITLE
Show sub-menu settings in Tools menu

### PR DESCRIPTION
**Pull request by PaulStoffregen**
This patch adds settings display in the Tools menu, for each sub-menu.  It's visually easy to see both the selected board and port, and any other custom menu settings, without having to position the mouse over each one, one at a time.

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
With this patch:
after

**Comment by PaulStoffregen** [comment]
Before this patch:
before

**Comment by Chris--A** [comment]
This looks like a useful change.

**Comment by 00alis** [comment]
I really like it as well!

**Comment by ffissore** [comment]
Thanks!

**Pull request merged**
