### PR TITLE
Change the CTRL+DELETE behaviour to delete the next word

### PR DESCRIPTION
**Pull request by avargas-nearsoft**
According to https://github.com/arduino/Arduino/issues/4778 , this restores the "normal" behaviour for the KeyStroke (CTRL | Command) + DELETE to delete only one word in front of cursor instead of the rest of the line.

### CODE REVIEW

**Comment by ivanebernal** [comment]
The keyStroke does delete the word in front of the caret. LGTM.

**Comment by avargas-nearsoft** [comment]
@cmaglie Could you take a look at this? I had some free time at work but now I think I could not take more time for the project. 
Thanks!

**Comment by cmaglie** [comment]
Thanks for the patch!

I tested and it works for Windows and Linux, but it should be handled differently for MacOSX: right now the short-cut is set as Cmd+Delete (since MacOSX uses Cmd instead of Ctrl as `MenuShortcutKeyMask`) but it really should be Alt+Delete.

Could you fix this? you can use the method `OSUtils.isMacOS()` to check if the IDE is running on MacOSX.

**Comment by avargas-nearsoft** [comment]
It now works on OSX.

**Comment by cmaglie** [comment]
Thank you!

**Comment by dtwaddell** [comment]
Thanks @avargas-nearsoft :D

**Comment by matthijskooijman** [comment]
Hm, I wonder if it would be cleaner to change this in https://github.com/arduino/Arduino/blob/master/app/src/processing/app/syntax/SketchTextAreaDefaultInputMap.java instead? AFAICS that's where the other Arduino-specific input map changes are made, and having a single one of them in some random method somewhere else just causes confusion...

**Pull request merged**
