### PR TITLE
[STEPPER] Improvements to C++ code

### PR DESCRIPTION
**Pull request by steve-weinrich**
- There are no functionality or interface changes.  Just C++ improvements.
- Use a "pointer to member function" to divide "stepMotor" into discrete methods.
- Remove unnecessary use of "this".
- Add a common initialization method for use by all constructors.
- Add appropriate use of "const".
- Remove "direction" from class as it was only used in one method.
- Add "numberOfPositions" so that the "step" method does not need to test the motor type.
- Change the "motorPins" into an array to make common initialization easier.
- Use camel case variable names instead of underscores.

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @steve-weinrich ,
would you mind moving the PR to https://github.com/arduino-libraries/Stepper/pulls ? Thanks

**Comment by steve-weinrich** [comment]
Howdy,

No problem.  Do you want me to integrate the other PR’s into this?  Or just certain ones?  Or none?

Cheers.

**Comment by facchinm** [comment]
Feel free to create a brand new PR with all your commits included :wink:

**Comment by steve-weinrich** [comment]
Moving to arduino-libraries

**Pull request closed without merging**
