### PR TITLE
fixes arduino/Arduino#4460

### PR DESCRIPTION
**Pull request by nharrand**
Fixes arduino/Arduino#4460
(Problem with print(char c, int base) and print(int i, int base)

### CODE REVIEW

**Comment by Lyadis** [comment]
Ok I fixed the indentation problem.
You were right about the unsigned char, and unsigned int. The problem came in fact from the fact that if you call `print(char c, int base)`, int is in fact `print(int i, int base)` which is called with a conversion char to int. 
I propose to fix it by adding a function `print(char c, int base)` without the implicit base=DEC in order not mess up with print(char c).
About the `& masking`, it seems to be required. I think when you do a conversion int to unsigned long, your value is first extended to 4 bytes then read as an unsigned long.

**Comment by Lyadis** [comment]
About the cost, I think if both existing and new functions are used, we are looking at 82 bytes more. (If I am not mistaken)

**Comment by matthijskooijman** [comment]
>  About the & masking, it seems to be required. I think when you do a conversion int to unsigned long, your value is first extended to 4 bytes then read as an unsigned long.

It's probably also solvable by first casting to unsigned int, and then to unsigned long. Could you try that?

> About the cost, I think if both previously existing and new functions are used, we are looking at 82 bytes more in the program space. (If I am not mistaken). (I calculated it by compiling the same program with both version of the library)

Hm, that sounds like much to me, but that's probably because there is an extra function now. How much is the difference for a program only printing a char, and for a program only printing an int?

Also, shouldn't the `println(int, int)` function also be adapted?

**Comment by Lyadis** [comment]
After running the test on 
```
void setup() {
  Serial.begin(9600);
  char c = -1;
  Serial.print(c, HEX);
  Serial.print((int) c, HEX);
}
void loop() {}
```
It actually cost 84 more bytes to use the version propsed in this PR.
I think it is due to gcc optimization. When we have:
```
size_t Print::print(int n, int base)
{
  return print((long) n, base);
}
```
print(int, int) is in fact just a renaming of print(long, int) (with a conversion in the parameter).
I suspect that gcc just replace calls for print(int, int) and do not define a new symbol for the function. But when the function contains an if statment, I guess that gcc don't have enough information at compile time to optimize in the same way... This is just speculation.

About the masking compare to double conversion: Surprisingly double conversion actually cost 2 bytes per conversion.

About `println(int, int)`, as it relies on `print(int, int)`, it doesn't need any fixes.

**Comment by Chris--A** [comment]
I posted a response  to the issue here.

I personally do not think this is needed at all. Signed to unsigned conversions are well defined and the behavior of sign bit extension is expected.

https://github.com/arduino/Arduino/issues/4460#issuecomment-174243539

**Pull request closed without merging**
