### PR TITLE
Create parser.ino

### PR DESCRIPTION
**Pull request by martinius96**
Parser for Ethernet shield W5100 for parsing variable from .txt file also  usable for read response from php request.
You can use it easy for control relays from webserver, speech to text recongnition (voice control) etc. IoT, Smart Home.

### CODE REVIEW

**Comment by martinius96** [comment]
Usable for example?

**Comment by Rotzbua** [comment]
Better move your pr to the original repo: https://github.com/arduino-libraries/Ethernet
Also you should auto format your code by arduino ide.
Best

**Comment by facchinm** [comment]
Hi @martinius96 , examples are meant to be way more generic than yours (no paypal links for example) , and they need to be fully written in English so everyone can understand.

**Comment by martinius96** [comment]
Okay, so :-) Parser will be only mine :*

**Pull request closed without merging**
