### PR TITLE
Call on onBoardOrPortChange after selectBoard when board argument passed into command line

### PR DESCRIPTION
**Pull request by sandeepmistry**
Implements same behaviour as the GUI when a board is changed via the menu.

I was having issues with the build failing because the library path for previous architecture was used for bundled libraries like Wire.

### CODE REVIEW

**Comment by ffissore** [comment]
Can you provide a sequence of steps for reproducing the issue?

**Comment by sandeepmistry** [comment]
Steps to reproduce:

1) Create WireTest sketch:
```c
#include <Wire.h>

void setup() {
}

void loop() {
}
```

2) Build for Uno
```sh
/Applications/Arduino.app/Contents/MacOS/Arduino --verbose-build --verify --board arduino:avr:uno ~/Documents/Arduino/WireTest/WireTest.ino
```

3) Build for Due

```sh
/Applications/Arduino.app/Contents/MacOS/Arduino --verbose-build --verify --board arduino:sam:arduino_due_x_dbg ~/Documents/Arduino/WireTest/WireTest.ino
```

I get the following error:
```
/Users/smistry/Documents/Arduino/hardware/arduino/avr/libraries/Wire/Wire.cpp: In member function 'void TwoWire::setClock(uint32_t)':
/Users/smistry/Documents/Arduino/hardware/arduino/avr/libraries/Wire/Wire.cpp:85:3: error: 'TWBR' was not declared in this scope
   TWBR = ((F_CPU / frequency) - 16) / 2;
   ^
Error compiling.
```

As AVR Wire library header is being included instead of SAM.

**Comment by matthijskooijman** [comment]
At first glance, the change looks good to me. I'm not sure if this bug has been around for a long time and just not noticed, or if there used to be some call the ``onBoardOrPortChange()`` later in the process that has been refactored away, but this change looks ok to me in any case.

**Comment by ffissore** [comment]
Thanks!

**Pull request merged**
