### PR TITLE
making UART/USART handler weak to allow custom external handlers

### PR DESCRIPTION
**Pull request by ricardocrudo**
I've opened a thread about this here: https://groups.google.com/a/arduino.cc/forum/#!topic/developers/FIjuI4z06tY

### CODE REVIEW

**Comment by NicoHood** [comment]
I'd also suggest to do this for AVR if possible

**Comment by ricardocrudo** [comment]
The AVR one uses the ISR macro, probably define it again in the user code will work.

**Comment by ricardocrudo** [comment]
polite bump

**Comment by facchinm** [comment]
Moved to arduino/ArduinoCore-sam#1

**Pull request closed without merging**
