### PR TITLE
Various improvements in build script

### PR DESCRIPTION
**Pull request by cmaglie**
This PR contains the following fixes:

* the IDE is now tolerant to missing `package_index_bundled.json`
* the IDE is now tolerant to missing bundled `libraries` folder or missing `sketchbook/librarires`
* the build script task `arduino-builder-build` has been factored out, so it's now more maintainable (one task for all architectures) and allow conditional build through env variable. This is based on @NicoHood's commit https://github.com/arduino/Arduino/pull/5438/commits/f29abf881d729b8b0d388fc275c5de33051b6e82

This should supersede and fix #5438 

/cc @NicoHood

### CODE REVIEW

**Comment by NicoHood** [comment]
Those commits are missing:
https://github.com/arduino/Arduino/pull/5438/commits/5de6c1fd2776072f3c520f2e8c79d125443fcdc5
https://github.com/arduino/Arduino/pull/5438/commits/4cee989558e10c69b20db78a88393a34715fa9bb

**Comment by NicoHood** [comment]
The IDE also should be tolerant of a missing arduino-tools folder:
https://bugs.archlinux.org/task/52377

Any chance to see a better fix?

**Comment by cmaglie** [comment]
> Those commits are missing:
> 5de6c1f
> 4cee989

Those are already cherry-picked in master branch:

d3bd5f22bdf1bbcf9efee745497ae0d16a516778
1da91087e410bf4b427906661e4feb43e291e342
8e6422ffd888c6aa989de107c78487fe9ee1f0c5

**Comment by cmaglie** [comment]
> The IDE also should be tolerant of a missing tools-builder folder:
> https://bugs.archlinux.org/task/52377
>
> Any chance to see a better fix?

How can I reproduce that?
Maybe you should open another issue, to better track this bug.

**Comment by NicoHood** [comment]
you need to delete the described folder (or better move it somewhere else) and change platform.txt to point to the new loation. make sure your .arduino15 folder does not exist, otherwise the bug is not triggered (as it is not for me)

**Comment by cmaglie** [comment]
It seems the builder that requires (at least) one `-tools` option, can you open an issue on the builder repository?

**Comment by NicoHood** [comment]
Fixes seem to be applied properly. Thanks a lot!

The only thing left for packaging arduino securely now are the gpg signatures:
https://github.com/arduino/Arduino/pull/5772#issuecomment-269777511

You can use my gpgit script which is straight forward and super easy with github:
https://github.com/NicoHood/gpgit

**Pull request merged**
