### PR TITLE
XFCE's Launcher wants the .desktop file to be +x as well

### PR DESCRIPTION
**Pull request by herrold**
-- add a --mode 755 for it

solves an issue in #4581

### CODE REVIEW

**Comment by facchinm** [comment]
From `xdg-desktop-menu` man page (http://manpages.ubuntu.com/manpages/zesty/man1/xdg-desktop-menu.1.html) it looks like `--mode` can only accept `user` or `system` as arguments, thus the patch would lead to failure when installing. I believe the `chmod +x` fix should be applied to `"${TMP_DIR}/${RESOURCE_NAME}.desktop"` and then `xdg-desktop-menu` should be called. Could you please double check the patch on another Linux distro? Thanks!

**Comment by herrold** [comment]
I will deploy a Ubuntu and see

**Comment by herrold** [comment]
It does appear in my Ubuntu that I was using the Unix 'free desktop' install hammer improperly .. 
I have reverted that, and moved the needed change into 'build.xml' ... 
testing locally

**Comment by herrold** [comment]
I have tested with the change at the ..xml build instructions per my revised pathc.  It seems to work just fine, and without the prior stderr noise
 
> Arduino-1  arduino-1.8.4-linux64.tar.xz  Arduino-daily-20170727
> [herrold@centos-7 herrold]$ mkdir testing
> [herrold@centos-7 herrold]$ cp arduino-1.8.4-linux64.tar.xz testing/
> [herrold@centos-7 herrold]$ cd testing/
> [herrold@centos-7 testing]$ unxz arduino-1.8.4-linux64.tar.xz
> [herrold@centos-7 testing]$ tar xf arduino-1.8.4-linux64.tar 
> [herrold@centos-7 testing]$ cd arduino-1.8.4/
> [herrold@centos-7 arduino-1.8.4]$ ./uninstall.sh
> Removing desktop shortcut and menu item for Arduino IDE... done!
> [herrold@centos-7 arduino-1.8.4]$ ./install.sh 
> Adding desktop shortcut, menu item and file associations for Arduino IDE... done!
> [herrold@centos-7 arduino-1.8.4]$ 

and manually inspecting the file:

> [herrold@centos-7 arduino-1.8.4]$ ls -al ~/Desktop/*desktop*
> -rwx------. 1 herrold herrold 402 Jul 27 13:34 /home/herrold/Desktop/arduino-arduinoide.desktop

Starting it with a 'terminal' window enabled is silent except for an error I have not tracked down yet:

     Picked up JAVA_TOOL_OPTIONS: 
     Error parsing gtk-icon-sizes string: ''


As such, I think this patch is ready to go production -- please re-review

**Pull request merged**
