### PR TITLE
Introducing Atmel toolchain 3.4.4

### PR DESCRIPTION
**Pull request by ffissore**
This PR introduces Atmel toolchain 3.4.4 (see http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/3.4.4/)
WRT to previous release (3.4.3), binutils has been upgraded to 2.24 and gdb has been added to the list of available command line tools

Be aware: this PR will be **rebased** from time to time.

### CODE REVIEW

**Comment by ffissore** [comment]
@ArduinoBot build this please

**Comment by PaoloP74** [comment]
New toolchain available --> http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/3.4.5/
You could skip the 3.4.4 release.

**Comment by ffissore** [comment]
Wow! Thanks for the heads up!

**Comment by ffissore** [comment]
Superseded by #2551

**Pull request closed without merging**
