### PR TITLE
Big IDE enchavements : New Editor,  AutoComplete, Doc Tooltips, New SyntaxColoring, etc... 

### PR DESCRIPTION
**Pull request by ricardojlrufino**
My Changes and work log : https://gist.github.com/ricardojlrufino/19f89884162be39d851a
General status:
- Autocomplete (90%)
- Realtime Parser and Error Marker(90%)
- Documentation in the Editor (in progress - 20%)

### CODE REVIEW

**Comment by dbarciela** [comment]
I'm running the IDE with this commit and I have to say, this is some amazing work

**Comment by ricardojlrufino** [comment]
@cmaglie , @dbarciela  - i did another implementation based on 1.6.2 branch, see on: 
https://github.com/OpenDevice/Arduino/tree/1.6.x-autocomplete-neweditor

I have done a release if someone want to test ....
http://criativasoft.com.br/downloads/programas/arduino/

**Comment by ricardojlrufino** [comment]
Thank you very much

I did another implementation based on 1.6.2 branch, see on:
https://github.com/OpenDevice/Arduino/tree/1.6.x-autocomplete-neweditor

I have done a release if someone want to test ....
http://criativasoft.com.br/downloads/programas/arduino/

I will prepare to integrate with version 1.6.3 that had many improvements.



Em dom, 19 de abr de 2015 às 14:06, dbarciela <notifications@github.com>
escreveu:

**Comment by LRagji** [comment]
Why is this not a part of the public mainstream release??

**Pull request closed without merging**
