### PR TITLE
Make Wire library error safe

### PR DESCRIPTION
**Pull request by MauroMombelli**
by adding timeout into twi and giving the user a way to use them.

Full retrocompatible.

### CODE REVIEW

**Comment by MauroMombelli** [comment]
is this still needed? i can fix to merge

**Comment by Jim4Beam** [comment]
I tried the Code with RTC DS3231 and DS3232RTC Lib from http://github.com/JChristensen/DS3232RTC under IDE 1.6.6 Ubuntu 14.04, it compiles, but dos NOT give correct readings from the RTC an Code still hangs if power of RTC is disconnected while communication is in progress. 

Serial output (should be: hh:mm:ss  dd.mm.yy Temp [°C])
01:18:09	11.10.41	655,1C	 
01:18:09	10.08.42	655,1C	 
01:18:09	29.08.43	0,0C

back with original wire and twi files it look like this - seems the RTC got reset, but at least Temp is fine:
01:28:05	01.01.00	23,7C
01:28:07	01.01.00	23,7C

after resetting RTC to correct time (all back good, but still hang problem if power is disc.):
16:05:03	25.11.15	23,7C	
16:05:05	25.11.15	23,7C

**Comment by MauroMombelli** [comment]
can you send me the code and the "raw" communication with the sensor?

**Comment by Jim4Beam** [comment]
Yes I will, but how can I record the raw I2C communication with the sensor? Thx

-----Original Message-----

**Comment by MauroMombelli** [comment]
just send back the data that come to i2c by serial, in hex format :)

**Comment by mjeveritt** [comment]
Any chance of fixing the conflicts for a review? @MauroMombelli ?

**Comment by MauroMombelli** [comment]
@mjeveritt not unless the devs show some interest

**Comment by mjeveritt** [comment]
> @mjeveritt not unless the devs show some interest

I suspect flying elephants will occur first ... :rofl:

**Comment by cmaglie** [comment]
@MauroMombelli @mjeveritt

you missed the news: the timeout is now implemented in AVR Wire
https://github.com/arduino/ArduinoCore-avr/blob/9f8d27f09f3bbd1da1374b5549a82bda55d45d44/libraries/Wire/src/Wire.h#L58

We closed all the issues related to the I2C/Wire timeout, but we missed this one.

Since you're interested in this discussion you may want to join the party here:
https://github.com/arduino/ArduinoCore-avr/issues/42

**Pull request closed without merging**
